// Generated by jextract

package com.github.tornaia.foreign.win.api.searchapi.internal;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import jdk.incubator.foreign.*;
import jdk.incubator.foreign.MemoryLayout.PathElement;
import static jdk.incubator.foreign.CLinker.*;
class searchapi_h$constants$2 extends searchapi_h$constants$1 {

    /* package-private */ searchapi_h$constants$2() {}
    static final MemoryLayout ISearchQueryHelperVtbl$put_QuerySorting$LAYOUT_ = C_POINTER;
    static final jdk.incubator.foreign.MemoryLayout ISearchQueryHelperVtbl$put_QuerySorting$LAYOUT() { return ISearchQueryHelperVtbl$put_QuerySorting$LAYOUT_; }

    static final VarHandle ISearchQueryHelperVtbl$put_QuerySorting$VH_ = MemoryHandles.asAddressVarHandle(ISearchQueryHelperVtbl$struct$LAYOUT_.varHandle(long.class, MemoryLayout.PathElement.groupElement("put_QuerySorting")));
    static final java.lang.invoke.VarHandle ISearchQueryHelperVtbl$put_QuerySorting$VH() { return ISearchQueryHelperVtbl$put_QuerySorting$VH_; }

    static final MemoryLayout ISearchQueryHelperVtbl$get_QuerySorting$LAYOUT_ = C_POINTER;
    static final jdk.incubator.foreign.MemoryLayout ISearchQueryHelperVtbl$get_QuerySorting$LAYOUT() { return ISearchQueryHelperVtbl$get_QuerySorting$LAYOUT_; }

    static final VarHandle ISearchQueryHelperVtbl$get_QuerySorting$VH_ = MemoryHandles.asAddressVarHandle(ISearchQueryHelperVtbl$struct$LAYOUT_.varHandle(long.class, MemoryLayout.PathElement.groupElement("get_QuerySorting")));
    static final java.lang.invoke.VarHandle ISearchQueryHelperVtbl$get_QuerySorting$VH() { return ISearchQueryHelperVtbl$get_QuerySorting$VH_; }

    static final MemoryLayout ISearchQueryHelperVtbl$GenerateSQLFromUserQuery$LAYOUT_ = C_POINTER;
    static final jdk.incubator.foreign.MemoryLayout ISearchQueryHelperVtbl$GenerateSQLFromUserQuery$LAYOUT() { return ISearchQueryHelperVtbl$GenerateSQLFromUserQuery$LAYOUT_; }

    static final VarHandle ISearchQueryHelperVtbl$GenerateSQLFromUserQuery$VH_ = MemoryHandles.asAddressVarHandle(ISearchQueryHelperVtbl$struct$LAYOUT_.varHandle(long.class, MemoryLayout.PathElement.groupElement("GenerateSQLFromUserQuery")));
    static final java.lang.invoke.VarHandle ISearchQueryHelperVtbl$GenerateSQLFromUserQuery$VH() { return ISearchQueryHelperVtbl$GenerateSQLFromUserQuery$VH_; }

    static final MemoryLayout ISearchQueryHelperVtbl$WriteProperties$LAYOUT_ = C_POINTER;
    static final jdk.incubator.foreign.MemoryLayout ISearchQueryHelperVtbl$WriteProperties$LAYOUT() { return ISearchQueryHelperVtbl$WriteProperties$LAYOUT_; }

    static final VarHandle ISearchQueryHelperVtbl$WriteProperties$VH_ = MemoryHandles.asAddressVarHandle(ISearchQueryHelperVtbl$struct$LAYOUT_.varHandle(long.class, MemoryLayout.PathElement.groupElement("WriteProperties")));
    static final java.lang.invoke.VarHandle ISearchQueryHelperVtbl$WriteProperties$VH() { return ISearchQueryHelperVtbl$WriteProperties$VH_; }

    static final MemoryLayout ISearchQueryHelperVtbl$put_QueryMaxResults$LAYOUT_ = C_POINTER;
    static final jdk.incubator.foreign.MemoryLayout ISearchQueryHelperVtbl$put_QueryMaxResults$LAYOUT() { return ISearchQueryHelperVtbl$put_QueryMaxResults$LAYOUT_; }

    static final VarHandle ISearchQueryHelperVtbl$put_QueryMaxResults$VH_ = MemoryHandles.asAddressVarHandle(ISearchQueryHelperVtbl$struct$LAYOUT_.varHandle(long.class, MemoryLayout.PathElement.groupElement("put_QueryMaxResults")));
    static final java.lang.invoke.VarHandle ISearchQueryHelperVtbl$put_QueryMaxResults$VH() { return ISearchQueryHelperVtbl$put_QueryMaxResults$VH_; }

    static final MemoryLayout ISearchQueryHelperVtbl$get_QueryMaxResults$LAYOUT_ = C_POINTER;
    static final jdk.incubator.foreign.MemoryLayout ISearchQueryHelperVtbl$get_QueryMaxResults$LAYOUT() { return ISearchQueryHelperVtbl$get_QueryMaxResults$LAYOUT_; }

    static final VarHandle ISearchQueryHelperVtbl$get_QueryMaxResults$VH_ = MemoryHandles.asAddressVarHandle(ISearchQueryHelperVtbl$struct$LAYOUT_.varHandle(long.class, MemoryLayout.PathElement.groupElement("get_QueryMaxResults")));
    static final java.lang.invoke.VarHandle ISearchQueryHelperVtbl$get_QueryMaxResults$VH() { return ISearchQueryHelperVtbl$get_QueryMaxResults$VH_; }

    static final MemoryLayout ISearchQueryHelper$struct$LAYOUT_ = MemoryLayout.ofStruct(
        C_POINTER.withName("lpVtbl")
    ).withName("ISearchQueryHelper");
    static final jdk.incubator.foreign.MemoryLayout ISearchQueryHelper$struct$LAYOUT() { return ISearchQueryHelper$struct$LAYOUT_; }

    static final MemoryLayout ISearchQueryHelper$lpVtbl$LAYOUT_ = C_POINTER;
    static final jdk.incubator.foreign.MemoryLayout ISearchQueryHelper$lpVtbl$LAYOUT() { return ISearchQueryHelper$lpVtbl$LAYOUT_; }

    static final VarHandle ISearchQueryHelper$lpVtbl$VH_ = MemoryHandles.asAddressVarHandle(ISearchQueryHelper$struct$LAYOUT_.varHandle(long.class, MemoryLayout.PathElement.groupElement("lpVtbl")));
    static final java.lang.invoke.VarHandle ISearchQueryHelper$lpVtbl$VH() { return ISearchQueryHelper$lpVtbl$VH_; }

    static final int PRIORITY_LEVEL_FOREGROUND() { return (int)0L; }

    static final int PRIORITY_LEVEL_HIGH() { return (int)1L; }

    static final int PRIORITY_LEVEL_LOW() { return (int)2L; }

    static final int PRIORITY_LEVEL_DEFAULT() { return (int)3L; }

    static final MemoryLayout __MIDL_itf_searchapi_0000_0022_v0_0_c_ifspec$LAYOUT_ = C_POINTER;
    static final jdk.incubator.foreign.MemoryLayout __MIDL_itf_searchapi_0000_0022_v0_0_c_ifspec$LAYOUT() { return __MIDL_itf_searchapi_0000_0022_v0_0_c_ifspec$LAYOUT_; }

    static final VarHandle __MIDL_itf_searchapi_0000_0022_v0_0_c_ifspec$VH_ = MemoryHandles.asAddressVarHandle(__MIDL_itf_searchapi_0000_0022_v0_0_c_ifspec$LAYOUT_.varHandle(long.class));
    static final java.lang.invoke.VarHandle __MIDL_itf_searchapi_0000_0022_v0_0_c_ifspec$VH() { return __MIDL_itf_searchapi_0000_0022_v0_0_c_ifspec$VH_; }

    static final MemorySegment __MIDL_itf_searchapi_0000_0022_v0_0_c_ifspec$SEGMENT_ = RuntimeHelper.lookupGlobalVariable(LIBRARIES, "__MIDL_itf_searchapi_0000_0022_v0_0_c_ifspec", __MIDL_itf_searchapi_0000_0022_v0_0_c_ifspec$LAYOUT_);
    static final jdk.incubator.foreign.MemorySegment __MIDL_itf_searchapi_0000_0022_v0_0_c_ifspec$SEGMENT() { return __MIDL_itf_searchapi_0000_0022_v0_0_c_ifspec$SEGMENT_; }

    static final MemoryLayout __MIDL_itf_searchapi_0000_0022_v0_0_s_ifspec$LAYOUT_ = C_POINTER;
    static final jdk.incubator.foreign.MemoryLayout __MIDL_itf_searchapi_0000_0022_v0_0_s_ifspec$LAYOUT() { return __MIDL_itf_searchapi_0000_0022_v0_0_s_ifspec$LAYOUT_; }

    static final VarHandle __MIDL_itf_searchapi_0000_0022_v0_0_s_ifspec$VH_ = MemoryHandles.asAddressVarHandle(__MIDL_itf_searchapi_0000_0022_v0_0_s_ifspec$LAYOUT_.varHandle(long.class));
    static final java.lang.invoke.VarHandle __MIDL_itf_searchapi_0000_0022_v0_0_s_ifspec$VH() { return __MIDL_itf_searchapi_0000_0022_v0_0_s_ifspec$VH_; }

    static final MemorySegment __MIDL_itf_searchapi_0000_0022_v0_0_s_ifspec$SEGMENT_ = RuntimeHelper.lookupGlobalVariable(LIBRARIES, "__MIDL_itf_searchapi_0000_0022_v0_0_s_ifspec", __MIDL_itf_searchapi_0000_0022_v0_0_s_ifspec$LAYOUT_);
    static final jdk.incubator.foreign.MemorySegment __MIDL_itf_searchapi_0000_0022_v0_0_s_ifspec$SEGMENT() { return __MIDL_itf_searchapi_0000_0022_v0_0_s_ifspec$SEGMENT_; }

    static final MemoryLayout IID_IRowsetPrioritization$LAYOUT_ = MemoryLayout.ofStruct(
        C_LONG.withName("Data1"),
        C_SHORT.withName("Data2"),
        C_SHORT.withName("Data3"),
        MemoryLayout.ofSequence(8, C_CHAR).withName("Data4")
    ).withName("_GUID");
    static final jdk.incubator.foreign.MemoryLayout IID_IRowsetPrioritization$LAYOUT() { return IID_IRowsetPrioritization$LAYOUT_; }

    static final MemorySegment IID_IRowsetPrioritization$SEGMENT_ = RuntimeHelper.lookupGlobalVariable(LIBRARIES, "IID_IRowsetPrioritization", IID_IRowsetPrioritization$LAYOUT_);
    static final jdk.incubator.foreign.MemorySegment IID_IRowsetPrioritization$SEGMENT() { return IID_IRowsetPrioritization$SEGMENT_; }

    static final MemoryLayout IRowsetPrioritizationVtbl$struct$LAYOUT_ = MemoryLayout.ofStruct(
        C_POINTER.withName("QueryInterface"),
        C_POINTER.withName("AddRef"),
        C_POINTER.withName("Release"),
        C_POINTER.withName("SetScopePriority"),
        C_POINTER.withName("GetScopePriority"),
        C_POINTER.withName("GetScopeStatistics")
    ).withName("IRowsetPrioritizationVtbl");
    static final jdk.incubator.foreign.MemoryLayout IRowsetPrioritizationVtbl$struct$LAYOUT() { return IRowsetPrioritizationVtbl$struct$LAYOUT_; }

    static final MemoryLayout IRowsetPrioritizationVtbl$QueryInterface$LAYOUT_ = C_POINTER;
    static final jdk.incubator.foreign.MemoryLayout IRowsetPrioritizationVtbl$QueryInterface$LAYOUT() { return IRowsetPrioritizationVtbl$QueryInterface$LAYOUT_; }

    static final VarHandle IRowsetPrioritizationVtbl$QueryInterface$VH_ = MemoryHandles.asAddressVarHandle(IRowsetPrioritizationVtbl$struct$LAYOUT_.varHandle(long.class, MemoryLayout.PathElement.groupElement("QueryInterface")));
    static final java.lang.invoke.VarHandle IRowsetPrioritizationVtbl$QueryInterface$VH() { return IRowsetPrioritizationVtbl$QueryInterface$VH_; }

    static final MemoryLayout IRowsetPrioritizationVtbl$AddRef$LAYOUT_ = C_POINTER;
    static final jdk.incubator.foreign.MemoryLayout IRowsetPrioritizationVtbl$AddRef$LAYOUT() { return IRowsetPrioritizationVtbl$AddRef$LAYOUT_; }

    static final VarHandle IRowsetPrioritizationVtbl$AddRef$VH_ = MemoryHandles.asAddressVarHandle(IRowsetPrioritizationVtbl$struct$LAYOUT_.varHandle(long.class, MemoryLayout.PathElement.groupElement("AddRef")));
    static final java.lang.invoke.VarHandle IRowsetPrioritizationVtbl$AddRef$VH() { return IRowsetPrioritizationVtbl$AddRef$VH_; }

    static final MemoryLayout IRowsetPrioritizationVtbl$Release$LAYOUT_ = C_POINTER;
    static final jdk.incubator.foreign.MemoryLayout IRowsetPrioritizationVtbl$Release$LAYOUT() { return IRowsetPrioritizationVtbl$Release$LAYOUT_; }

    static final VarHandle IRowsetPrioritizationVtbl$Release$VH_ = MemoryHandles.asAddressVarHandle(IRowsetPrioritizationVtbl$struct$LAYOUT_.varHandle(long.class, MemoryLayout.PathElement.groupElement("Release")));
    static final java.lang.invoke.VarHandle IRowsetPrioritizationVtbl$Release$VH() { return IRowsetPrioritizationVtbl$Release$VH_; }

    static final MemoryLayout IRowsetPrioritizationVtbl$SetScopePriority$LAYOUT_ = C_POINTER;
    static final jdk.incubator.foreign.MemoryLayout IRowsetPrioritizationVtbl$SetScopePriority$LAYOUT() { return IRowsetPrioritizationVtbl$SetScopePriority$LAYOUT_; }

    static final VarHandle IRowsetPrioritizationVtbl$SetScopePriority$VH_ = MemoryHandles.asAddressVarHandle(IRowsetPrioritizationVtbl$struct$LAYOUT_.varHandle(long.class, MemoryLayout.PathElement.groupElement("SetScopePriority")));
    static final java.lang.invoke.VarHandle IRowsetPrioritizationVtbl$SetScopePriority$VH() { return IRowsetPrioritizationVtbl$SetScopePriority$VH_; }

    static final MemoryLayout IRowsetPrioritizationVtbl$GetScopePriority$LAYOUT_ = C_POINTER;
    static final jdk.incubator.foreign.MemoryLayout IRowsetPrioritizationVtbl$GetScopePriority$LAYOUT() { return IRowsetPrioritizationVtbl$GetScopePriority$LAYOUT_; }

    static final VarHandle IRowsetPrioritizationVtbl$GetScopePriority$VH_ = MemoryHandles.asAddressVarHandle(IRowsetPrioritizationVtbl$struct$LAYOUT_.varHandle(long.class, MemoryLayout.PathElement.groupElement("GetScopePriority")));
    static final java.lang.invoke.VarHandle IRowsetPrioritizationVtbl$GetScopePriority$VH() { return IRowsetPrioritizationVtbl$GetScopePriority$VH_; }

    static final MemoryLayout IRowsetPrioritizationVtbl$GetScopeStatistics$LAYOUT_ = C_POINTER;
    static final jdk.incubator.foreign.MemoryLayout IRowsetPrioritizationVtbl$GetScopeStatistics$LAYOUT() { return IRowsetPrioritizationVtbl$GetScopeStatistics$LAYOUT_; }

    static final VarHandle IRowsetPrioritizationVtbl$GetScopeStatistics$VH_ = MemoryHandles.asAddressVarHandle(IRowsetPrioritizationVtbl$struct$LAYOUT_.varHandle(long.class, MemoryLayout.PathElement.groupElement("GetScopeStatistics")));
    static final java.lang.invoke.VarHandle IRowsetPrioritizationVtbl$GetScopeStatistics$VH() { return IRowsetPrioritizationVtbl$GetScopeStatistics$VH_; }

    static final MemoryLayout IRowsetPrioritization$struct$LAYOUT_ = MemoryLayout.ofStruct(
        C_POINTER.withName("lpVtbl")
    ).withName("IRowsetPrioritization");
    static final jdk.incubator.foreign.MemoryLayout IRowsetPrioritization$struct$LAYOUT() { return IRowsetPrioritization$struct$LAYOUT_; }

    static final MemoryLayout IRowsetPrioritization$lpVtbl$LAYOUT_ = C_POINTER;
    static final jdk.incubator.foreign.MemoryLayout IRowsetPrioritization$lpVtbl$LAYOUT() { return IRowsetPrioritization$lpVtbl$LAYOUT_; }

    static final VarHandle IRowsetPrioritization$lpVtbl$VH_ = MemoryHandles.asAddressVarHandle(IRowsetPrioritization$struct$LAYOUT_.varHandle(long.class, MemoryLayout.PathElement.groupElement("lpVtbl")));
    static final java.lang.invoke.VarHandle IRowsetPrioritization$lpVtbl$VH() { return IRowsetPrioritization$lpVtbl$VH_; }

    static final int ROWSETEVENT_ITEMSTATE_NOTINROWSET() { return (int)0L; }

    static final int ROWSETEVENT_ITEMSTATE_INROWSET() { return (int)1L; }

    static final int ROWSETEVENT_ITEMSTATE_UNKNOWN() { return (int)2L; }

    static final int ROWSETEVENT_TYPE_DATAEXPIRED() { return (int)0L; }

    static final int ROWSETEVENT_TYPE_FOREGROUNDLOST() { return (int)1L; }

    static final int ROWSETEVENT_TYPE_SCOPESTATISTICS() { return (int)2L; }

    static final MemoryLayout __MIDL_itf_searchapi_0000_0023_v0_0_c_ifspec$LAYOUT_ = C_POINTER;
    static final jdk.incubator.foreign.MemoryLayout __MIDL_itf_searchapi_0000_0023_v0_0_c_ifspec$LAYOUT() { return __MIDL_itf_searchapi_0000_0023_v0_0_c_ifspec$LAYOUT_; }

    static final VarHandle __MIDL_itf_searchapi_0000_0023_v0_0_c_ifspec$VH_ = MemoryHandles.asAddressVarHandle(__MIDL_itf_searchapi_0000_0023_v0_0_c_ifspec$LAYOUT_.varHandle(long.class));
    static final java.lang.invoke.VarHandle __MIDL_itf_searchapi_0000_0023_v0_0_c_ifspec$VH() { return __MIDL_itf_searchapi_0000_0023_v0_0_c_ifspec$VH_; }

    static final MemorySegment __MIDL_itf_searchapi_0000_0023_v0_0_c_ifspec$SEGMENT_ = RuntimeHelper.lookupGlobalVariable(LIBRARIES, "__MIDL_itf_searchapi_0000_0023_v0_0_c_ifspec", __MIDL_itf_searchapi_0000_0023_v0_0_c_ifspec$LAYOUT_);
    static final jdk.incubator.foreign.MemorySegment __MIDL_itf_searchapi_0000_0023_v0_0_c_ifspec$SEGMENT() { return __MIDL_itf_searchapi_0000_0023_v0_0_c_ifspec$SEGMENT_; }

    static final MemoryLayout __MIDL_itf_searchapi_0000_0023_v0_0_s_ifspec$LAYOUT_ = C_POINTER;
    static final jdk.incubator.foreign.MemoryLayout __MIDL_itf_searchapi_0000_0023_v0_0_s_ifspec$LAYOUT() { return __MIDL_itf_searchapi_0000_0023_v0_0_s_ifspec$LAYOUT_; }

    static final VarHandle __MIDL_itf_searchapi_0000_0023_v0_0_s_ifspec$VH_ = MemoryHandles.asAddressVarHandle(__MIDL_itf_searchapi_0000_0023_v0_0_s_ifspec$LAYOUT_.varHandle(long.class));
    static final java.lang.invoke.VarHandle __MIDL_itf_searchapi_0000_0023_v0_0_s_ifspec$VH() { return __MIDL_itf_searchapi_0000_0023_v0_0_s_ifspec$VH_; }

    static final MemorySegment __MIDL_itf_searchapi_0000_0023_v0_0_s_ifspec$SEGMENT_ = RuntimeHelper.lookupGlobalVariable(LIBRARIES, "__MIDL_itf_searchapi_0000_0023_v0_0_s_ifspec", __MIDL_itf_searchapi_0000_0023_v0_0_s_ifspec$LAYOUT_);
    static final jdk.incubator.foreign.MemorySegment __MIDL_itf_searchapi_0000_0023_v0_0_s_ifspec$SEGMENT() { return __MIDL_itf_searchapi_0000_0023_v0_0_s_ifspec$SEGMENT_; }

    static final MemoryLayout IID_IRowsetEvents$LAYOUT_ = MemoryLayout.ofStruct(
        C_LONG.withName("Data1"),
        C_SHORT.withName("Data2"),
        C_SHORT.withName("Data3"),
        MemoryLayout.ofSequence(8, C_CHAR).withName("Data4")
    ).withName("_GUID");
    static final jdk.incubator.foreign.MemoryLayout IID_IRowsetEvents$LAYOUT() { return IID_IRowsetEvents$LAYOUT_; }

    static final MemorySegment IID_IRowsetEvents$SEGMENT_ = RuntimeHelper.lookupGlobalVariable(LIBRARIES, "IID_IRowsetEvents", IID_IRowsetEvents$LAYOUT_);
    static final jdk.incubator.foreign.MemorySegment IID_IRowsetEvents$SEGMENT() { return IID_IRowsetEvents$SEGMENT_; }

    static final MemoryLayout IRowsetEventsVtbl$struct$LAYOUT_ = MemoryLayout.ofStruct(
        C_POINTER.withName("QueryInterface"),
        C_POINTER.withName("AddRef"),
        C_POINTER.withName("Release"),
        C_POINTER.withName("OnNewItem"),
        C_POINTER.withName("OnChangedItem"),
        C_POINTER.withName("OnDeletedItem"),
        C_POINTER.withName("OnRowsetEvent")
    ).withName("IRowsetEventsVtbl");
    static final jdk.incubator.foreign.MemoryLayout IRowsetEventsVtbl$struct$LAYOUT() { return IRowsetEventsVtbl$struct$LAYOUT_; }

    static final MemoryLayout IRowsetEventsVtbl$QueryInterface$LAYOUT_ = C_POINTER;
    static final jdk.incubator.foreign.MemoryLayout IRowsetEventsVtbl$QueryInterface$LAYOUT() { return IRowsetEventsVtbl$QueryInterface$LAYOUT_; }

    static final VarHandle IRowsetEventsVtbl$QueryInterface$VH_ = MemoryHandles.asAddressVarHandle(IRowsetEventsVtbl$struct$LAYOUT_.varHandle(long.class, MemoryLayout.PathElement.groupElement("QueryInterface")));
    static final java.lang.invoke.VarHandle IRowsetEventsVtbl$QueryInterface$VH() { return IRowsetEventsVtbl$QueryInterface$VH_; }

    static final MemoryLayout IRowsetEventsVtbl$AddRef$LAYOUT_ = C_POINTER;
    static final jdk.incubator.foreign.MemoryLayout IRowsetEventsVtbl$AddRef$LAYOUT() { return IRowsetEventsVtbl$AddRef$LAYOUT_; }

    static final VarHandle IRowsetEventsVtbl$AddRef$VH_ = MemoryHandles.asAddressVarHandle(IRowsetEventsVtbl$struct$LAYOUT_.varHandle(long.class, MemoryLayout.PathElement.groupElement("AddRef")));
    static final java.lang.invoke.VarHandle IRowsetEventsVtbl$AddRef$VH() { return IRowsetEventsVtbl$AddRef$VH_; }

    static final MemoryLayout IRowsetEventsVtbl$Release$LAYOUT_ = C_POINTER;
    static final jdk.incubator.foreign.MemoryLayout IRowsetEventsVtbl$Release$LAYOUT() { return IRowsetEventsVtbl$Release$LAYOUT_; }

    static final VarHandle IRowsetEventsVtbl$Release$VH_ = MemoryHandles.asAddressVarHandle(IRowsetEventsVtbl$struct$LAYOUT_.varHandle(long.class, MemoryLayout.PathElement.groupElement("Release")));
    static final java.lang.invoke.VarHandle IRowsetEventsVtbl$Release$VH() { return IRowsetEventsVtbl$Release$VH_; }

    static final MemoryLayout IRowsetEventsVtbl$OnNewItem$LAYOUT_ = C_POINTER;
    static final jdk.incubator.foreign.MemoryLayout IRowsetEventsVtbl$OnNewItem$LAYOUT() { return IRowsetEventsVtbl$OnNewItem$LAYOUT_; }

    static final VarHandle IRowsetEventsVtbl$OnNewItem$VH_ = MemoryHandles.asAddressVarHandle(IRowsetEventsVtbl$struct$LAYOUT_.varHandle(long.class, MemoryLayout.PathElement.groupElement("OnNewItem")));
    static final java.lang.invoke.VarHandle IRowsetEventsVtbl$OnNewItem$VH() { return IRowsetEventsVtbl$OnNewItem$VH_; }

    static final MemoryLayout IRowsetEventsVtbl$OnChangedItem$LAYOUT_ = C_POINTER;
    static final jdk.incubator.foreign.MemoryLayout IRowsetEventsVtbl$OnChangedItem$LAYOUT() { return IRowsetEventsVtbl$OnChangedItem$LAYOUT_; }

    static final VarHandle IRowsetEventsVtbl$OnChangedItem$VH_ = MemoryHandles.asAddressVarHandle(IRowsetEventsVtbl$struct$LAYOUT_.varHandle(long.class, MemoryLayout.PathElement.groupElement("OnChangedItem")));
    static final java.lang.invoke.VarHandle IRowsetEventsVtbl$OnChangedItem$VH() { return IRowsetEventsVtbl$OnChangedItem$VH_; }

    static final MemoryLayout IRowsetEventsVtbl$OnDeletedItem$LAYOUT_ = C_POINTER;
    static final jdk.incubator.foreign.MemoryLayout IRowsetEventsVtbl$OnDeletedItem$LAYOUT() { return IRowsetEventsVtbl$OnDeletedItem$LAYOUT_; }

    static final VarHandle IRowsetEventsVtbl$OnDeletedItem$VH_ = MemoryHandles.asAddressVarHandle(IRowsetEventsVtbl$struct$LAYOUT_.varHandle(long.class, MemoryLayout.PathElement.groupElement("OnDeletedItem")));
    static final java.lang.invoke.VarHandle IRowsetEventsVtbl$OnDeletedItem$VH() { return IRowsetEventsVtbl$OnDeletedItem$VH_; }

    static final MemoryLayout IRowsetEventsVtbl$OnRowsetEvent$LAYOUT_ = C_POINTER;
    static final jdk.incubator.foreign.MemoryLayout IRowsetEventsVtbl$OnRowsetEvent$LAYOUT() { return IRowsetEventsVtbl$OnRowsetEvent$LAYOUT_; }

    static final VarHandle IRowsetEventsVtbl$OnRowsetEvent$VH_ = MemoryHandles.asAddressVarHandle(IRowsetEventsVtbl$struct$LAYOUT_.varHandle(long.class, MemoryLayout.PathElement.groupElement("OnRowsetEvent")));
    static final java.lang.invoke.VarHandle IRowsetEventsVtbl$OnRowsetEvent$VH() { return IRowsetEventsVtbl$OnRowsetEvent$VH_; }

    static final MemoryLayout IRowsetEvents$struct$LAYOUT_ = MemoryLayout.ofStruct(
        C_POINTER.withName("lpVtbl")
    ).withName("IRowsetEvents");
    static final jdk.incubator.foreign.MemoryLayout IRowsetEvents$struct$LAYOUT() { return IRowsetEvents$struct$LAYOUT_; }

    static final MemoryLayout IRowsetEvents$lpVtbl$LAYOUT_ = C_POINTER;
    static final jdk.incubator.foreign.MemoryLayout IRowsetEvents$lpVtbl$LAYOUT() { return IRowsetEvents$lpVtbl$LAYOUT_; }

    static final VarHandle IRowsetEvents$lpVtbl$VH_ = MemoryHandles.asAddressVarHandle(IRowsetEvents$struct$LAYOUT_.varHandle(long.class, MemoryLayout.PathElement.groupElement("lpVtbl")));
    static final java.lang.invoke.VarHandle IRowsetEvents$lpVtbl$VH() { return IRowsetEvents$lpVtbl$VH_; }

    static final MemoryLayout __MIDL_itf_searchapi_0000_0024_v0_0_c_ifspec$LAYOUT_ = C_POINTER;
    static final jdk.incubator.foreign.MemoryLayout __MIDL_itf_searchapi_0000_0024_v0_0_c_ifspec$LAYOUT() { return __MIDL_itf_searchapi_0000_0024_v0_0_c_ifspec$LAYOUT_; }

    static final VarHandle __MIDL_itf_searchapi_0000_0024_v0_0_c_ifspec$VH_ = MemoryHandles.asAddressVarHandle(__MIDL_itf_searchapi_0000_0024_v0_0_c_ifspec$LAYOUT_.varHandle(long.class));
    static final java.lang.invoke.VarHandle __MIDL_itf_searchapi_0000_0024_v0_0_c_ifspec$VH() { return __MIDL_itf_searchapi_0000_0024_v0_0_c_ifspec$VH_; }

    static final MemorySegment __MIDL_itf_searchapi_0000_0024_v0_0_c_ifspec$SEGMENT_ = RuntimeHelper.lookupGlobalVariable(LIBRARIES, "__MIDL_itf_searchapi_0000_0024_v0_0_c_ifspec", __MIDL_itf_searchapi_0000_0024_v0_0_c_ifspec$LAYOUT_);
    static final jdk.incubator.foreign.MemorySegment __MIDL_itf_searchapi_0000_0024_v0_0_c_ifspec$SEGMENT() { return __MIDL_itf_searchapi_0000_0024_v0_0_c_ifspec$SEGMENT_; }

    static final MemoryLayout __MIDL_itf_searchapi_0000_0024_v0_0_s_ifspec$LAYOUT_ = C_POINTER;
    static final jdk.incubator.foreign.MemoryLayout __MIDL_itf_searchapi_0000_0024_v0_0_s_ifspec$LAYOUT() { return __MIDL_itf_searchapi_0000_0024_v0_0_s_ifspec$LAYOUT_; }

    static final VarHandle __MIDL_itf_searchapi_0000_0024_v0_0_s_ifspec$VH_ = MemoryHandles.asAddressVarHandle(__MIDL_itf_searchapi_0000_0024_v0_0_s_ifspec$LAYOUT_.varHandle(long.class));
    static final java.lang.invoke.VarHandle __MIDL_itf_searchapi_0000_0024_v0_0_s_ifspec$VH() { return __MIDL_itf_searchapi_0000_0024_v0_0_s_ifspec$VH_; }

    static final MemorySegment __MIDL_itf_searchapi_0000_0024_v0_0_s_ifspec$SEGMENT_ = RuntimeHelper.lookupGlobalVariable(LIBRARIES, "__MIDL_itf_searchapi_0000_0024_v0_0_s_ifspec", __MIDL_itf_searchapi_0000_0024_v0_0_s_ifspec$LAYOUT_);
    static final jdk.incubator.foreign.MemorySegment __MIDL_itf_searchapi_0000_0024_v0_0_s_ifspec$SEGMENT() { return __MIDL_itf_searchapi_0000_0024_v0_0_s_ifspec$SEGMENT_; }

    static final MemoryLayout IID_ISearchManager$LAYOUT_ = MemoryLayout.ofStruct(
        C_LONG.withName("Data1"),
        C_SHORT.withName("Data2"),
        C_SHORT.withName("Data3"),
        MemoryLayout.ofSequence(8, C_CHAR).withName("Data4")
    ).withName("_GUID");
    static final jdk.incubator.foreign.MemoryLayout IID_ISearchManager$LAYOUT() { return IID_ISearchManager$LAYOUT_; }

    static final MemorySegment IID_ISearchManager$SEGMENT_ = RuntimeHelper.lookupGlobalVariable(LIBRARIES, "IID_ISearchManager", IID_ISearchManager$LAYOUT_);
    static final jdk.incubator.foreign.MemorySegment IID_ISearchManager$SEGMENT() { return IID_ISearchManager$SEGMENT_; }

    static final MemoryLayout ISearchManagerVtbl$struct$LAYOUT_ = MemoryLayout.ofStruct(
        C_POINTER.withName("QueryInterface"),
        C_POINTER.withName("AddRef"),
        C_POINTER.withName("Release"),
        C_POINTER.withName("GetIndexerVersionStr"),
        C_POINTER.withName("GetIndexerVersion"),
        C_POINTER.withName("GetParameter"),
        C_POINTER.withName("SetParameter"),
        C_POINTER.withName("get_ProxyName"),
        C_POINTER.withName("get_BypassList"),
        C_POINTER.withName("SetProxy"),
        C_POINTER.withName("GetCatalog"),
        C_POINTER.withName("get_UserAgent"),
        C_POINTER.withName("put_UserAgent"),
        C_POINTER.withName("get_UseProxy"),
        C_POINTER.withName("get_LocalBypass"),
        C_POINTER.withName("get_PortNumber")
    ).withName("ISearchManagerVtbl");
    static final jdk.incubator.foreign.MemoryLayout ISearchManagerVtbl$struct$LAYOUT() { return ISearchManagerVtbl$struct$LAYOUT_; }

    static final MemoryLayout ISearchManagerVtbl$QueryInterface$LAYOUT_ = C_POINTER;
    static final jdk.incubator.foreign.MemoryLayout ISearchManagerVtbl$QueryInterface$LAYOUT() { return ISearchManagerVtbl$QueryInterface$LAYOUT_; }

    static final VarHandle ISearchManagerVtbl$QueryInterface$VH_ = MemoryHandles.asAddressVarHandle(ISearchManagerVtbl$struct$LAYOUT_.varHandle(long.class, MemoryLayout.PathElement.groupElement("QueryInterface")));
    static final java.lang.invoke.VarHandle ISearchManagerVtbl$QueryInterface$VH() { return ISearchManagerVtbl$QueryInterface$VH_; }

    static final MemoryLayout ISearchManagerVtbl$AddRef$LAYOUT_ = C_POINTER;
    static final jdk.incubator.foreign.MemoryLayout ISearchManagerVtbl$AddRef$LAYOUT() { return ISearchManagerVtbl$AddRef$LAYOUT_; }

    static final VarHandle ISearchManagerVtbl$AddRef$VH_ = MemoryHandles.asAddressVarHandle(ISearchManagerVtbl$struct$LAYOUT_.varHandle(long.class, MemoryLayout.PathElement.groupElement("AddRef")));
    static final java.lang.invoke.VarHandle ISearchManagerVtbl$AddRef$VH() { return ISearchManagerVtbl$AddRef$VH_; }

    static final MemoryLayout ISearchManagerVtbl$Release$LAYOUT_ = C_POINTER;
    static final jdk.incubator.foreign.MemoryLayout ISearchManagerVtbl$Release$LAYOUT() { return ISearchManagerVtbl$Release$LAYOUT_; }

    static final VarHandle ISearchManagerVtbl$Release$VH_ = MemoryHandles.asAddressVarHandle(ISearchManagerVtbl$struct$LAYOUT_.varHandle(long.class, MemoryLayout.PathElement.groupElement("Release")));
    static final java.lang.invoke.VarHandle ISearchManagerVtbl$Release$VH() { return ISearchManagerVtbl$Release$VH_; }

    static final MemoryLayout ISearchManagerVtbl$GetIndexerVersionStr$LAYOUT_ = C_POINTER;
    static final jdk.incubator.foreign.MemoryLayout ISearchManagerVtbl$GetIndexerVersionStr$LAYOUT() { return ISearchManagerVtbl$GetIndexerVersionStr$LAYOUT_; }

    static final VarHandle ISearchManagerVtbl$GetIndexerVersionStr$VH_ = MemoryHandles.asAddressVarHandle(ISearchManagerVtbl$struct$LAYOUT_.varHandle(long.class, MemoryLayout.PathElement.groupElement("GetIndexerVersionStr")));
    static final java.lang.invoke.VarHandle ISearchManagerVtbl$GetIndexerVersionStr$VH() { return ISearchManagerVtbl$GetIndexerVersionStr$VH_; }

    static final MemoryLayout ISearchManagerVtbl$GetIndexerVersion$LAYOUT_ = C_POINTER;
    static final jdk.incubator.foreign.MemoryLayout ISearchManagerVtbl$GetIndexerVersion$LAYOUT() { return ISearchManagerVtbl$GetIndexerVersion$LAYOUT_; }

    static final VarHandle ISearchManagerVtbl$GetIndexerVersion$VH_ = MemoryHandles.asAddressVarHandle(ISearchManagerVtbl$struct$LAYOUT_.varHandle(long.class, MemoryLayout.PathElement.groupElement("GetIndexerVersion")));
    static final java.lang.invoke.VarHandle ISearchManagerVtbl$GetIndexerVersion$VH() { return ISearchManagerVtbl$GetIndexerVersion$VH_; }

    static final MemoryLayout ISearchManagerVtbl$GetParameter$LAYOUT_ = C_POINTER;
    static final jdk.incubator.foreign.MemoryLayout ISearchManagerVtbl$GetParameter$LAYOUT() { return ISearchManagerVtbl$GetParameter$LAYOUT_; }

    static final VarHandle ISearchManagerVtbl$GetParameter$VH_ = MemoryHandles.asAddressVarHandle(ISearchManagerVtbl$struct$LAYOUT_.varHandle(long.class, MemoryLayout.PathElement.groupElement("GetParameter")));
    static final java.lang.invoke.VarHandle ISearchManagerVtbl$GetParameter$VH() { return ISearchManagerVtbl$GetParameter$VH_; }

    static final MemoryLayout ISearchManagerVtbl$SetParameter$LAYOUT_ = C_POINTER;
    static final jdk.incubator.foreign.MemoryLayout ISearchManagerVtbl$SetParameter$LAYOUT() { return ISearchManagerVtbl$SetParameter$LAYOUT_; }

    static final VarHandle ISearchManagerVtbl$SetParameter$VH_ = MemoryHandles.asAddressVarHandle(ISearchManagerVtbl$struct$LAYOUT_.varHandle(long.class, MemoryLayout.PathElement.groupElement("SetParameter")));
    static final java.lang.invoke.VarHandle ISearchManagerVtbl$SetParameter$VH() { return ISearchManagerVtbl$SetParameter$VH_; }

    static final MemoryLayout ISearchManagerVtbl$get_ProxyName$LAYOUT_ = C_POINTER;
    static final jdk.incubator.foreign.MemoryLayout ISearchManagerVtbl$get_ProxyName$LAYOUT() { return ISearchManagerVtbl$get_ProxyName$LAYOUT_; }

    static final VarHandle ISearchManagerVtbl$get_ProxyName$VH_ = MemoryHandles.asAddressVarHandle(ISearchManagerVtbl$struct$LAYOUT_.varHandle(long.class, MemoryLayout.PathElement.groupElement("get_ProxyName")));
    static final java.lang.invoke.VarHandle ISearchManagerVtbl$get_ProxyName$VH() { return ISearchManagerVtbl$get_ProxyName$VH_; }

    static final MemoryLayout ISearchManagerVtbl$get_BypassList$LAYOUT_ = C_POINTER;
    static final jdk.incubator.foreign.MemoryLayout ISearchManagerVtbl$get_BypassList$LAYOUT() { return ISearchManagerVtbl$get_BypassList$LAYOUT_; }

    static final VarHandle ISearchManagerVtbl$get_BypassList$VH_ = MemoryHandles.asAddressVarHandle(ISearchManagerVtbl$struct$LAYOUT_.varHandle(long.class, MemoryLayout.PathElement.groupElement("get_BypassList")));
    static final java.lang.invoke.VarHandle ISearchManagerVtbl$get_BypassList$VH() { return ISearchManagerVtbl$get_BypassList$VH_; }

    static final MemoryLayout ISearchManagerVtbl$SetProxy$LAYOUT_ = C_POINTER;
    static final jdk.incubator.foreign.MemoryLayout ISearchManagerVtbl$SetProxy$LAYOUT() { return ISearchManagerVtbl$SetProxy$LAYOUT_; }

    static final VarHandle ISearchManagerVtbl$SetProxy$VH_ = MemoryHandles.asAddressVarHandle(ISearchManagerVtbl$struct$LAYOUT_.varHandle(long.class, MemoryLayout.PathElement.groupElement("SetProxy")));
    static final java.lang.invoke.VarHandle ISearchManagerVtbl$SetProxy$VH() { return ISearchManagerVtbl$SetProxy$VH_; }

    static final MemoryLayout ISearchManagerVtbl$GetCatalog$LAYOUT_ = C_POINTER;
    static final jdk.incubator.foreign.MemoryLayout ISearchManagerVtbl$GetCatalog$LAYOUT() { return ISearchManagerVtbl$GetCatalog$LAYOUT_; }

    static final VarHandle ISearchManagerVtbl$GetCatalog$VH_ = MemoryHandles.asAddressVarHandle(ISearchManagerVtbl$struct$LAYOUT_.varHandle(long.class, MemoryLayout.PathElement.groupElement("GetCatalog")));
    static final java.lang.invoke.VarHandle ISearchManagerVtbl$GetCatalog$VH() { return ISearchManagerVtbl$GetCatalog$VH_; }

    static final MemoryLayout ISearchManagerVtbl$get_UserAgent$LAYOUT_ = C_POINTER;
    static final jdk.incubator.foreign.MemoryLayout ISearchManagerVtbl$get_UserAgent$LAYOUT() { return ISearchManagerVtbl$get_UserAgent$LAYOUT_; }

    static final VarHandle ISearchManagerVtbl$get_UserAgent$VH_ = MemoryHandles.asAddressVarHandle(ISearchManagerVtbl$struct$LAYOUT_.varHandle(long.class, MemoryLayout.PathElement.groupElement("get_UserAgent")));
    static final java.lang.invoke.VarHandle ISearchManagerVtbl$get_UserAgent$VH() { return ISearchManagerVtbl$get_UserAgent$VH_; }

    static final MemoryLayout ISearchManagerVtbl$put_UserAgent$LAYOUT_ = C_POINTER;
    static final jdk.incubator.foreign.MemoryLayout ISearchManagerVtbl$put_UserAgent$LAYOUT() { return ISearchManagerVtbl$put_UserAgent$LAYOUT_; }

    static final VarHandle ISearchManagerVtbl$put_UserAgent$VH_ = MemoryHandles.asAddressVarHandle(ISearchManagerVtbl$struct$LAYOUT_.varHandle(long.class, MemoryLayout.PathElement.groupElement("put_UserAgent")));
    static final java.lang.invoke.VarHandle ISearchManagerVtbl$put_UserAgent$VH() { return ISearchManagerVtbl$put_UserAgent$VH_; }

    static final MemoryLayout ISearchManagerVtbl$get_UseProxy$LAYOUT_ = C_POINTER;
    static final jdk.incubator.foreign.MemoryLayout ISearchManagerVtbl$get_UseProxy$LAYOUT() { return ISearchManagerVtbl$get_UseProxy$LAYOUT_; }

    static final VarHandle ISearchManagerVtbl$get_UseProxy$VH_ = MemoryHandles.asAddressVarHandle(ISearchManagerVtbl$struct$LAYOUT_.varHandle(long.class, MemoryLayout.PathElement.groupElement("get_UseProxy")));
    static final java.lang.invoke.VarHandle ISearchManagerVtbl$get_UseProxy$VH() { return ISearchManagerVtbl$get_UseProxy$VH_; }

    static final MemoryLayout ISearchManagerVtbl$get_LocalBypass$LAYOUT_ = C_POINTER;
    static final jdk.incubator.foreign.MemoryLayout ISearchManagerVtbl$get_LocalBypass$LAYOUT() { return ISearchManagerVtbl$get_LocalBypass$LAYOUT_; }

    static final VarHandle ISearchManagerVtbl$get_LocalBypass$VH_ = MemoryHandles.asAddressVarHandle(ISearchManagerVtbl$struct$LAYOUT_.varHandle(long.class, MemoryLayout.PathElement.groupElement("get_LocalBypass")));
    static final java.lang.invoke.VarHandle ISearchManagerVtbl$get_LocalBypass$VH() { return ISearchManagerVtbl$get_LocalBypass$VH_; }

    static final MemoryLayout ISearchManagerVtbl$get_PortNumber$LAYOUT_ = C_POINTER;
    static final jdk.incubator.foreign.MemoryLayout ISearchManagerVtbl$get_PortNumber$LAYOUT() { return ISearchManagerVtbl$get_PortNumber$LAYOUT_; }

    static final VarHandle ISearchManagerVtbl$get_PortNumber$VH_ = MemoryHandles.asAddressVarHandle(ISearchManagerVtbl$struct$LAYOUT_.varHandle(long.class, MemoryLayout.PathElement.groupElement("get_PortNumber")));
    static final java.lang.invoke.VarHandle ISearchManagerVtbl$get_PortNumber$VH() { return ISearchManagerVtbl$get_PortNumber$VH_; }

    static final MemoryLayout ISearchManager$struct$LAYOUT_ = MemoryLayout.ofStruct(
        C_POINTER.withName("lpVtbl")
    ).withName("ISearchManager");
    static final jdk.incubator.foreign.MemoryLayout ISearchManager$struct$LAYOUT() { return ISearchManager$struct$LAYOUT_; }

    static final MemoryLayout ISearchManager$lpVtbl$LAYOUT_ = C_POINTER;
    static final jdk.incubator.foreign.MemoryLayout ISearchManager$lpVtbl$LAYOUT() { return ISearchManager$lpVtbl$LAYOUT_; }

    static final VarHandle ISearchManager$lpVtbl$VH_ = MemoryHandles.asAddressVarHandle(ISearchManager$struct$LAYOUT_.varHandle(long.class, MemoryLayout.PathElement.groupElement("lpVtbl")));
    static final java.lang.invoke.VarHandle ISearchManager$lpVtbl$VH() { return ISearchManager$lpVtbl$VH_; }

    static final MemoryLayout IID_ISearchManager2$LAYOUT_ = MemoryLayout.ofStruct(
        C_LONG.withName("Data1"),
        C_SHORT.withName("Data2"),
        C_SHORT.withName("Data3"),
        MemoryLayout.ofSequence(8, C_CHAR).withName("Data4")
    ).withName("_GUID");
    static final jdk.incubator.foreign.MemoryLayout IID_ISearchManager2$LAYOUT() { return IID_ISearchManager2$LAYOUT_; }

    static final MemorySegment IID_ISearchManager2$SEGMENT_ = RuntimeHelper.lookupGlobalVariable(LIBRARIES, "IID_ISearchManager2", IID_ISearchManager2$LAYOUT_);
    static final jdk.incubator.foreign.MemorySegment IID_ISearchManager2$SEGMENT() { return IID_ISearchManager2$SEGMENT_; }

    static final MemoryLayout ISearchManager2Vtbl$struct$LAYOUT_ = MemoryLayout.ofStruct(
        C_POINTER.withName("QueryInterface"),
        C_POINTER.withName("AddRef"),
        C_POINTER.withName("Release"),
        C_POINTER.withName("GetIndexerVersionStr"),
        C_POINTER.withName("GetIndexerVersion"),
        C_POINTER.withName("GetParameter"),
        C_POINTER.withName("SetParameter"),
        C_POINTER.withName("get_ProxyName"),
        C_POINTER.withName("get_BypassList"),
        C_POINTER.withName("SetProxy"),
        C_POINTER.withName("GetCatalog"),
        C_POINTER.withName("get_UserAgent"),
        C_POINTER.withName("put_UserAgent"),
        C_POINTER.withName("get_UseProxy"),
        C_POINTER.withName("get_LocalBypass"),
        C_POINTER.withName("get_PortNumber"),
        C_POINTER.withName("CreateCatalog"),
        C_POINTER.withName("DeleteCatalog")
    ).withName("ISearchManager2Vtbl");
    static final jdk.incubator.foreign.MemoryLayout ISearchManager2Vtbl$struct$LAYOUT() { return ISearchManager2Vtbl$struct$LAYOUT_; }

    static final MemoryLayout ISearchManager2Vtbl$QueryInterface$LAYOUT_ = C_POINTER;
    static final jdk.incubator.foreign.MemoryLayout ISearchManager2Vtbl$QueryInterface$LAYOUT() { return ISearchManager2Vtbl$QueryInterface$LAYOUT_; }

    static final VarHandle ISearchManager2Vtbl$QueryInterface$VH_ = MemoryHandles.asAddressVarHandle(ISearchManager2Vtbl$struct$LAYOUT_.varHandle(long.class, MemoryLayout.PathElement.groupElement("QueryInterface")));
    static final java.lang.invoke.VarHandle ISearchManager2Vtbl$QueryInterface$VH() { return ISearchManager2Vtbl$QueryInterface$VH_; }

    static final MemoryLayout ISearchManager2Vtbl$AddRef$LAYOUT_ = C_POINTER;
    static final jdk.incubator.foreign.MemoryLayout ISearchManager2Vtbl$AddRef$LAYOUT() { return ISearchManager2Vtbl$AddRef$LAYOUT_; }

    static final VarHandle ISearchManager2Vtbl$AddRef$VH_ = MemoryHandles.asAddressVarHandle(ISearchManager2Vtbl$struct$LAYOUT_.varHandle(long.class, MemoryLayout.PathElement.groupElement("AddRef")));
    static final java.lang.invoke.VarHandle ISearchManager2Vtbl$AddRef$VH() { return ISearchManager2Vtbl$AddRef$VH_; }

    static final MemoryLayout ISearchManager2Vtbl$Release$LAYOUT_ = C_POINTER;
    static final jdk.incubator.foreign.MemoryLayout ISearchManager2Vtbl$Release$LAYOUT() { return ISearchManager2Vtbl$Release$LAYOUT_; }

    static final VarHandle ISearchManager2Vtbl$Release$VH_ = MemoryHandles.asAddressVarHandle(ISearchManager2Vtbl$struct$LAYOUT_.varHandle(long.class, MemoryLayout.PathElement.groupElement("Release")));
    static final java.lang.invoke.VarHandle ISearchManager2Vtbl$Release$VH() { return ISearchManager2Vtbl$Release$VH_; }

    static final MemoryLayout ISearchManager2Vtbl$GetIndexerVersionStr$LAYOUT_ = C_POINTER;
    static final jdk.incubator.foreign.MemoryLayout ISearchManager2Vtbl$GetIndexerVersionStr$LAYOUT() { return ISearchManager2Vtbl$GetIndexerVersionStr$LAYOUT_; }

    static final VarHandle ISearchManager2Vtbl$GetIndexerVersionStr$VH_ = MemoryHandles.asAddressVarHandle(ISearchManager2Vtbl$struct$LAYOUT_.varHandle(long.class, MemoryLayout.PathElement.groupElement("GetIndexerVersionStr")));
    static final java.lang.invoke.VarHandle ISearchManager2Vtbl$GetIndexerVersionStr$VH() { return ISearchManager2Vtbl$GetIndexerVersionStr$VH_; }

    static final MemoryLayout ISearchManager2Vtbl$GetIndexerVersion$LAYOUT_ = C_POINTER;
    static final jdk.incubator.foreign.MemoryLayout ISearchManager2Vtbl$GetIndexerVersion$LAYOUT() { return ISearchManager2Vtbl$GetIndexerVersion$LAYOUT_; }

    static final VarHandle ISearchManager2Vtbl$GetIndexerVersion$VH_ = MemoryHandles.asAddressVarHandle(ISearchManager2Vtbl$struct$LAYOUT_.varHandle(long.class, MemoryLayout.PathElement.groupElement("GetIndexerVersion")));
    static final java.lang.invoke.VarHandle ISearchManager2Vtbl$GetIndexerVersion$VH() { return ISearchManager2Vtbl$GetIndexerVersion$VH_; }

    static final MemoryLayout ISearchManager2Vtbl$GetParameter$LAYOUT_ = C_POINTER;
    static final jdk.incubator.foreign.MemoryLayout ISearchManager2Vtbl$GetParameter$LAYOUT() { return ISearchManager2Vtbl$GetParameter$LAYOUT_; }

    static final VarHandle ISearchManager2Vtbl$GetParameter$VH_ = MemoryHandles.asAddressVarHandle(ISearchManager2Vtbl$struct$LAYOUT_.varHandle(long.class, MemoryLayout.PathElement.groupElement("GetParameter")));
    static final java.lang.invoke.VarHandle ISearchManager2Vtbl$GetParameter$VH() { return ISearchManager2Vtbl$GetParameter$VH_; }

    static final MemoryLayout ISearchManager2Vtbl$SetParameter$LAYOUT_ = C_POINTER;
    static final jdk.incubator.foreign.MemoryLayout ISearchManager2Vtbl$SetParameter$LAYOUT() { return ISearchManager2Vtbl$SetParameter$LAYOUT_; }

    static final VarHandle ISearchManager2Vtbl$SetParameter$VH_ = MemoryHandles.asAddressVarHandle(ISearchManager2Vtbl$struct$LAYOUT_.varHandle(long.class, MemoryLayout.PathElement.groupElement("SetParameter")));
    static final java.lang.invoke.VarHandle ISearchManager2Vtbl$SetParameter$VH() { return ISearchManager2Vtbl$SetParameter$VH_; }

    static final MemoryLayout ISearchManager2Vtbl$get_ProxyName$LAYOUT_ = C_POINTER;
    static final jdk.incubator.foreign.MemoryLayout ISearchManager2Vtbl$get_ProxyName$LAYOUT() { return ISearchManager2Vtbl$get_ProxyName$LAYOUT_; }

    static final VarHandle ISearchManager2Vtbl$get_ProxyName$VH_ = MemoryHandles.asAddressVarHandle(ISearchManager2Vtbl$struct$LAYOUT_.varHandle(long.class, MemoryLayout.PathElement.groupElement("get_ProxyName")));
    static final java.lang.invoke.VarHandle ISearchManager2Vtbl$get_ProxyName$VH() { return ISearchManager2Vtbl$get_ProxyName$VH_; }

    static final MemoryLayout ISearchManager2Vtbl$get_BypassList$LAYOUT_ = C_POINTER;
    static final jdk.incubator.foreign.MemoryLayout ISearchManager2Vtbl$get_BypassList$LAYOUT() { return ISearchManager2Vtbl$get_BypassList$LAYOUT_; }

    static final VarHandle ISearchManager2Vtbl$get_BypassList$VH_ = MemoryHandles.asAddressVarHandle(ISearchManager2Vtbl$struct$LAYOUT_.varHandle(long.class, MemoryLayout.PathElement.groupElement("get_BypassList")));
    static final java.lang.invoke.VarHandle ISearchManager2Vtbl$get_BypassList$VH() { return ISearchManager2Vtbl$get_BypassList$VH_; }

    static final MemoryLayout ISearchManager2Vtbl$SetProxy$LAYOUT_ = C_POINTER;
    static final jdk.incubator.foreign.MemoryLayout ISearchManager2Vtbl$SetProxy$LAYOUT() { return ISearchManager2Vtbl$SetProxy$LAYOUT_; }

    static final VarHandle ISearchManager2Vtbl$SetProxy$VH_ = MemoryHandles.asAddressVarHandle(ISearchManager2Vtbl$struct$LAYOUT_.varHandle(long.class, MemoryLayout.PathElement.groupElement("SetProxy")));
    static final java.lang.invoke.VarHandle ISearchManager2Vtbl$SetProxy$VH() { return ISearchManager2Vtbl$SetProxy$VH_; }

    static final MemoryLayout ISearchManager2Vtbl$GetCatalog$LAYOUT_ = C_POINTER;
    static final jdk.incubator.foreign.MemoryLayout ISearchManager2Vtbl$GetCatalog$LAYOUT() { return ISearchManager2Vtbl$GetCatalog$LAYOUT_; }

    static final VarHandle ISearchManager2Vtbl$GetCatalog$VH_ = MemoryHandles.asAddressVarHandle(ISearchManager2Vtbl$struct$LAYOUT_.varHandle(long.class, MemoryLayout.PathElement.groupElement("GetCatalog")));
    static final java.lang.invoke.VarHandle ISearchManager2Vtbl$GetCatalog$VH() { return ISearchManager2Vtbl$GetCatalog$VH_; }

    static final MemoryLayout ISearchManager2Vtbl$get_UserAgent$LAYOUT_ = C_POINTER;
    static final jdk.incubator.foreign.MemoryLayout ISearchManager2Vtbl$get_UserAgent$LAYOUT() { return ISearchManager2Vtbl$get_UserAgent$LAYOUT_; }

    static final VarHandle ISearchManager2Vtbl$get_UserAgent$VH_ = MemoryHandles.asAddressVarHandle(ISearchManager2Vtbl$struct$LAYOUT_.varHandle(long.class, MemoryLayout.PathElement.groupElement("get_UserAgent")));
    static final java.lang.invoke.VarHandle ISearchManager2Vtbl$get_UserAgent$VH() { return ISearchManager2Vtbl$get_UserAgent$VH_; }

    static final MemoryLayout ISearchManager2Vtbl$put_UserAgent$LAYOUT_ = C_POINTER;
    static final jdk.incubator.foreign.MemoryLayout ISearchManager2Vtbl$put_UserAgent$LAYOUT() { return ISearchManager2Vtbl$put_UserAgent$LAYOUT_; }

    static final VarHandle ISearchManager2Vtbl$put_UserAgent$VH_ = MemoryHandles.asAddressVarHandle(ISearchManager2Vtbl$struct$LAYOUT_.varHandle(long.class, MemoryLayout.PathElement.groupElement("put_UserAgent")));
    static final java.lang.invoke.VarHandle ISearchManager2Vtbl$put_UserAgent$VH() { return ISearchManager2Vtbl$put_UserAgent$VH_; }

    static final MemoryLayout ISearchManager2Vtbl$get_UseProxy$LAYOUT_ = C_POINTER;
    static final jdk.incubator.foreign.MemoryLayout ISearchManager2Vtbl$get_UseProxy$LAYOUT() { return ISearchManager2Vtbl$get_UseProxy$LAYOUT_; }

    static final VarHandle ISearchManager2Vtbl$get_UseProxy$VH_ = MemoryHandles.asAddressVarHandle(ISearchManager2Vtbl$struct$LAYOUT_.varHandle(long.class, MemoryLayout.PathElement.groupElement("get_UseProxy")));
    static final java.lang.invoke.VarHandle ISearchManager2Vtbl$get_UseProxy$VH() { return ISearchManager2Vtbl$get_UseProxy$VH_; }

    static final MemoryLayout ISearchManager2Vtbl$get_LocalBypass$LAYOUT_ = C_POINTER;
    static final jdk.incubator.foreign.MemoryLayout ISearchManager2Vtbl$get_LocalBypass$LAYOUT() { return ISearchManager2Vtbl$get_LocalBypass$LAYOUT_; }

    static final VarHandle ISearchManager2Vtbl$get_LocalBypass$VH_ = MemoryHandles.asAddressVarHandle(ISearchManager2Vtbl$struct$LAYOUT_.varHandle(long.class, MemoryLayout.PathElement.groupElement("get_LocalBypass")));
    static final java.lang.invoke.VarHandle ISearchManager2Vtbl$get_LocalBypass$VH() { return ISearchManager2Vtbl$get_LocalBypass$VH_; }

    static final MemoryLayout ISearchManager2Vtbl$get_PortNumber$LAYOUT_ = C_POINTER;
    static final jdk.incubator.foreign.MemoryLayout ISearchManager2Vtbl$get_PortNumber$LAYOUT() { return ISearchManager2Vtbl$get_PortNumber$LAYOUT_; }

    static final VarHandle ISearchManager2Vtbl$get_PortNumber$VH_ = MemoryHandles.asAddressVarHandle(ISearchManager2Vtbl$struct$LAYOUT_.varHandle(long.class, MemoryLayout.PathElement.groupElement("get_PortNumber")));
    static final java.lang.invoke.VarHandle ISearchManager2Vtbl$get_PortNumber$VH() { return ISearchManager2Vtbl$get_PortNumber$VH_; }

    static final MemoryLayout ISearchManager2Vtbl$CreateCatalog$LAYOUT_ = C_POINTER;
    static final jdk.incubator.foreign.MemoryLayout ISearchManager2Vtbl$CreateCatalog$LAYOUT() { return ISearchManager2Vtbl$CreateCatalog$LAYOUT_; }

    static final VarHandle ISearchManager2Vtbl$CreateCatalog$VH_ = MemoryHandles.asAddressVarHandle(ISearchManager2Vtbl$struct$LAYOUT_.varHandle(long.class, MemoryLayout.PathElement.groupElement("CreateCatalog")));
    static final java.lang.invoke.VarHandle ISearchManager2Vtbl$CreateCatalog$VH() { return ISearchManager2Vtbl$CreateCatalog$VH_; }

    static final MemoryLayout ISearchManager2Vtbl$DeleteCatalog$LAYOUT_ = C_POINTER;
    static final jdk.incubator.foreign.MemoryLayout ISearchManager2Vtbl$DeleteCatalog$LAYOUT() { return ISearchManager2Vtbl$DeleteCatalog$LAYOUT_; }

    static final VarHandle ISearchManager2Vtbl$DeleteCatalog$VH_ = MemoryHandles.asAddressVarHandle(ISearchManager2Vtbl$struct$LAYOUT_.varHandle(long.class, MemoryLayout.PathElement.groupElement("DeleteCatalog")));
    static final java.lang.invoke.VarHandle ISearchManager2Vtbl$DeleteCatalog$VH() { return ISearchManager2Vtbl$DeleteCatalog$VH_; }

    static final MemoryLayout ISearchManager2$struct$LAYOUT_ = MemoryLayout.ofStruct(
        C_POINTER.withName("lpVtbl")
    ).withName("ISearchManager2");
    static final jdk.incubator.foreign.MemoryLayout ISearchManager2$struct$LAYOUT() { return ISearchManager2$struct$LAYOUT_; }

    static final MemoryLayout ISearchManager2$lpVtbl$LAYOUT_ = C_POINTER;
    static final jdk.incubator.foreign.MemoryLayout ISearchManager2$lpVtbl$LAYOUT() { return ISearchManager2$lpVtbl$LAYOUT_; }

    static final VarHandle ISearchManager2$lpVtbl$VH_ = MemoryHandles.asAddressVarHandle(ISearchManager2$struct$LAYOUT_.varHandle(long.class, MemoryLayout.PathElement.groupElement("lpVtbl")));
    static final java.lang.invoke.VarHandle ISearchManager2$lpVtbl$VH() { return ISearchManager2$lpVtbl$VH_; }

    static final MemoryLayout CLSID_CSearchLanguageSupport$LAYOUT_ = MemoryLayout.ofStruct(
        C_LONG.withName("Data1"),
        C_SHORT.withName("Data2"),
        C_SHORT.withName("Data3"),
        MemoryLayout.ofSequence(8, C_CHAR).withName("Data4")
    ).withName("_GUID");
    static final jdk.incubator.foreign.MemoryLayout CLSID_CSearchLanguageSupport$LAYOUT() { return CLSID_CSearchLanguageSupport$LAYOUT_; }

    static final MemorySegment CLSID_CSearchLanguageSupport$SEGMENT_ = RuntimeHelper.lookupGlobalVariable(LIBRARIES, "CLSID_CSearchLanguageSupport", CLSID_CSearchLanguageSupport$LAYOUT_);
    static final jdk.incubator.foreign.MemorySegment CLSID_CSearchLanguageSupport$SEGMENT() { return CLSID_CSearchLanguageSupport$SEGMENT_; }

    static final MemoryLayout __MIDL_itf_searchapi_0000_0026_v0_0_c_ifspec$LAYOUT_ = C_POINTER;
    static final jdk.incubator.foreign.MemoryLayout __MIDL_itf_searchapi_0000_0026_v0_0_c_ifspec$LAYOUT() { return __MIDL_itf_searchapi_0000_0026_v0_0_c_ifspec$LAYOUT_; }

    static final VarHandle __MIDL_itf_searchapi_0000_0026_v0_0_c_ifspec$VH_ = MemoryHandles.asAddressVarHandle(__MIDL_itf_searchapi_0000_0026_v0_0_c_ifspec$LAYOUT_.varHandle(long.class));
    static final java.lang.invoke.VarHandle __MIDL_itf_searchapi_0000_0026_v0_0_c_ifspec$VH() { return __MIDL_itf_searchapi_0000_0026_v0_0_c_ifspec$VH_; }

    static final MemorySegment __MIDL_itf_searchapi_0000_0026_v0_0_c_ifspec$SEGMENT_ = RuntimeHelper.lookupGlobalVariable(LIBRARIES, "__MIDL_itf_searchapi_0000_0026_v0_0_c_ifspec", __MIDL_itf_searchapi_0000_0026_v0_0_c_ifspec$LAYOUT_);
    static final jdk.incubator.foreign.MemorySegment __MIDL_itf_searchapi_0000_0026_v0_0_c_ifspec$SEGMENT() { return __MIDL_itf_searchapi_0000_0026_v0_0_c_ifspec$SEGMENT_; }

    static final MemoryLayout __MIDL_itf_searchapi_0000_0026_v0_0_s_ifspec$LAYOUT_ = C_POINTER;
    static final jdk.incubator.foreign.MemoryLayout __MIDL_itf_searchapi_0000_0026_v0_0_s_ifspec$LAYOUT() { return __MIDL_itf_searchapi_0000_0026_v0_0_s_ifspec$LAYOUT_; }

    static final VarHandle __MIDL_itf_searchapi_0000_0026_v0_0_s_ifspec$VH_ = MemoryHandles.asAddressVarHandle(__MIDL_itf_searchapi_0000_0026_v0_0_s_ifspec$LAYOUT_.varHandle(long.class));
    static final java.lang.invoke.VarHandle __MIDL_itf_searchapi_0000_0026_v0_0_s_ifspec$VH() { return __MIDL_itf_searchapi_0000_0026_v0_0_s_ifspec$VH_; }

    static final MemorySegment __MIDL_itf_searchapi_0000_0026_v0_0_s_ifspec$SEGMENT_ = RuntimeHelper.lookupGlobalVariable(LIBRARIES, "__MIDL_itf_searchapi_0000_0026_v0_0_s_ifspec", __MIDL_itf_searchapi_0000_0026_v0_0_s_ifspec$LAYOUT_);
    static final jdk.incubator.foreign.MemorySegment __MIDL_itf_searchapi_0000_0026_v0_0_s_ifspec$SEGMENT() { return __MIDL_itf_searchapi_0000_0026_v0_0_s_ifspec$SEGMENT_; }

    static final MemoryLayout IID_ISearchLanguageSupport$LAYOUT_ = MemoryLayout.ofStruct(
        C_LONG.withName("Data1"),
        C_SHORT.withName("Data2"),
        C_SHORT.withName("Data3"),
        MemoryLayout.ofSequence(8, C_CHAR).withName("Data4")
    ).withName("_GUID");
    static final jdk.incubator.foreign.MemoryLayout IID_ISearchLanguageSupport$LAYOUT() { return IID_ISearchLanguageSupport$LAYOUT_; }

    static final MemorySegment IID_ISearchLanguageSupport$SEGMENT_ = RuntimeHelper.lookupGlobalVariable(LIBRARIES, "IID_ISearchLanguageSupport", IID_ISearchLanguageSupport$LAYOUT_);
    static final jdk.incubator.foreign.MemorySegment IID_ISearchLanguageSupport$SEGMENT() { return IID_ISearchLanguageSupport$SEGMENT_; }

    static final MemoryLayout ISearchLanguageSupportVtbl$struct$LAYOUT_ = MemoryLayout.ofStruct(
        C_POINTER.withName("QueryInterface"),
        C_POINTER.withName("AddRef"),
        C_POINTER.withName("Release"),
        C_POINTER.withName("SetDiacriticSensitivity"),
        C_POINTER.withName("GetDiacriticSensitivity"),
        C_POINTER.withName("LoadWordBreaker"),
        C_POINTER.withName("LoadStemmer"),
        C_POINTER.withName("IsPrefixNormalized")
    ).withName("ISearchLanguageSupportVtbl");
    static final jdk.incubator.foreign.MemoryLayout ISearchLanguageSupportVtbl$struct$LAYOUT() { return ISearchLanguageSupportVtbl$struct$LAYOUT_; }

    static final MemoryLayout ISearchLanguageSupportVtbl$QueryInterface$LAYOUT_ = C_POINTER;
    static final jdk.incubator.foreign.MemoryLayout ISearchLanguageSupportVtbl$QueryInterface$LAYOUT() { return ISearchLanguageSupportVtbl$QueryInterface$LAYOUT_; }

    static final VarHandle ISearchLanguageSupportVtbl$QueryInterface$VH_ = MemoryHandles.asAddressVarHandle(ISearchLanguageSupportVtbl$struct$LAYOUT_.varHandle(long.class, MemoryLayout.PathElement.groupElement("QueryInterface")));
    static final java.lang.invoke.VarHandle ISearchLanguageSupportVtbl$QueryInterface$VH() { return ISearchLanguageSupportVtbl$QueryInterface$VH_; }

    static final MemoryLayout ISearchLanguageSupportVtbl$AddRef$LAYOUT_ = C_POINTER;
    static final jdk.incubator.foreign.MemoryLayout ISearchLanguageSupportVtbl$AddRef$LAYOUT() { return ISearchLanguageSupportVtbl$AddRef$LAYOUT_; }

    static final VarHandle ISearchLanguageSupportVtbl$AddRef$VH_ = MemoryHandles.asAddressVarHandle(ISearchLanguageSupportVtbl$struct$LAYOUT_.varHandle(long.class, MemoryLayout.PathElement.groupElement("AddRef")));
    static final java.lang.invoke.VarHandle ISearchLanguageSupportVtbl$AddRef$VH() { return ISearchLanguageSupportVtbl$AddRef$VH_; }

    static final MemoryLayout ISearchLanguageSupportVtbl$Release$LAYOUT_ = C_POINTER;
    static final jdk.incubator.foreign.MemoryLayout ISearchLanguageSupportVtbl$Release$LAYOUT() { return ISearchLanguageSupportVtbl$Release$LAYOUT_; }

    static final VarHandle ISearchLanguageSupportVtbl$Release$VH_ = MemoryHandles.asAddressVarHandle(ISearchLanguageSupportVtbl$struct$LAYOUT_.varHandle(long.class, MemoryLayout.PathElement.groupElement("Release")));
    static final java.lang.invoke.VarHandle ISearchLanguageSupportVtbl$Release$VH() { return ISearchLanguageSupportVtbl$Release$VH_; }

    static final MemoryLayout ISearchLanguageSupportVtbl$SetDiacriticSensitivity$LAYOUT_ = C_POINTER;
    static final jdk.incubator.foreign.MemoryLayout ISearchLanguageSupportVtbl$SetDiacriticSensitivity$LAYOUT() { return ISearchLanguageSupportVtbl$SetDiacriticSensitivity$LAYOUT_; }

    static final VarHandle ISearchLanguageSupportVtbl$SetDiacriticSensitivity$VH_ = MemoryHandles.asAddressVarHandle(ISearchLanguageSupportVtbl$struct$LAYOUT_.varHandle(long.class, MemoryLayout.PathElement.groupElement("SetDiacriticSensitivity")));
    static final java.lang.invoke.VarHandle ISearchLanguageSupportVtbl$SetDiacriticSensitivity$VH() { return ISearchLanguageSupportVtbl$SetDiacriticSensitivity$VH_; }

    static final MemoryLayout ISearchLanguageSupportVtbl$GetDiacriticSensitivity$LAYOUT_ = C_POINTER;
    static final jdk.incubator.foreign.MemoryLayout ISearchLanguageSupportVtbl$GetDiacriticSensitivity$LAYOUT() { return ISearchLanguageSupportVtbl$GetDiacriticSensitivity$LAYOUT_; }

    static final VarHandle ISearchLanguageSupportVtbl$GetDiacriticSensitivity$VH_ = MemoryHandles.asAddressVarHandle(ISearchLanguageSupportVtbl$struct$LAYOUT_.varHandle(long.class, MemoryLayout.PathElement.groupElement("GetDiacriticSensitivity")));
    static final java.lang.invoke.VarHandle ISearchLanguageSupportVtbl$GetDiacriticSensitivity$VH() { return ISearchLanguageSupportVtbl$GetDiacriticSensitivity$VH_; }

    static final MemoryLayout ISearchLanguageSupportVtbl$LoadWordBreaker$LAYOUT_ = C_POINTER;
    static final jdk.incubator.foreign.MemoryLayout ISearchLanguageSupportVtbl$LoadWordBreaker$LAYOUT() { return ISearchLanguageSupportVtbl$LoadWordBreaker$LAYOUT_; }

    static final VarHandle ISearchLanguageSupportVtbl$LoadWordBreaker$VH_ = MemoryHandles.asAddressVarHandle(ISearchLanguageSupportVtbl$struct$LAYOUT_.varHandle(long.class, MemoryLayout.PathElement.groupElement("LoadWordBreaker")));
    static final java.lang.invoke.VarHandle ISearchLanguageSupportVtbl$LoadWordBreaker$VH() { return ISearchLanguageSupportVtbl$LoadWordBreaker$VH_; }

    static final MemoryLayout ISearchLanguageSupportVtbl$LoadStemmer$LAYOUT_ = C_POINTER;
    static final jdk.incubator.foreign.MemoryLayout ISearchLanguageSupportVtbl$LoadStemmer$LAYOUT() { return ISearchLanguageSupportVtbl$LoadStemmer$LAYOUT_; }

    static final VarHandle ISearchLanguageSupportVtbl$LoadStemmer$VH_ = MemoryHandles.asAddressVarHandle(ISearchLanguageSupportVtbl$struct$LAYOUT_.varHandle(long.class, MemoryLayout.PathElement.groupElement("LoadStemmer")));
    static final java.lang.invoke.VarHandle ISearchLanguageSupportVtbl$LoadStemmer$VH() { return ISearchLanguageSupportVtbl$LoadStemmer$VH_; }

    static final MemoryLayout ISearchLanguageSupportVtbl$IsPrefixNormalized$LAYOUT_ = C_POINTER;
    static final jdk.incubator.foreign.MemoryLayout ISearchLanguageSupportVtbl$IsPrefixNormalized$LAYOUT() { return ISearchLanguageSupportVtbl$IsPrefixNormalized$LAYOUT_; }

    static final VarHandle ISearchLanguageSupportVtbl$IsPrefixNormalized$VH_ = MemoryHandles.asAddressVarHandle(ISearchLanguageSupportVtbl$struct$LAYOUT_.varHandle(long.class, MemoryLayout.PathElement.groupElement("IsPrefixNormalized")));
    static final java.lang.invoke.VarHandle ISearchLanguageSupportVtbl$IsPrefixNormalized$VH() { return ISearchLanguageSupportVtbl$IsPrefixNormalized$VH_; }

    static final MemoryLayout ISearchLanguageSupport$struct$LAYOUT_ = MemoryLayout.ofStruct(
        C_POINTER.withName("lpVtbl")
    ).withName("ISearchLanguageSupport");
    static final jdk.incubator.foreign.MemoryLayout ISearchLanguageSupport$struct$LAYOUT() { return ISearchLanguageSupport$struct$LAYOUT_; }

    static final MemoryLayout ISearchLanguageSupport$lpVtbl$LAYOUT_ = C_POINTER;
    static final jdk.incubator.foreign.MemoryLayout ISearchLanguageSupport$lpVtbl$LAYOUT() { return ISearchLanguageSupport$lpVtbl$LAYOUT_; }

    static final VarHandle ISearchLanguageSupport$lpVtbl$VH_ = MemoryHandles.asAddressVarHandle(ISearchLanguageSupport$struct$LAYOUT_.varHandle(long.class, MemoryLayout.PathElement.groupElement("lpVtbl")));
    static final java.lang.invoke.VarHandle ISearchLanguageSupport$lpVtbl$VH() { return ISearchLanguageSupport$lpVtbl$VH_; }

    static final MemoryLayout __MIDL_itf_searchapi_0000_0027_v0_0_c_ifspec$LAYOUT_ = C_POINTER;
    static final jdk.incubator.foreign.MemoryLayout __MIDL_itf_searchapi_0000_0027_v0_0_c_ifspec$LAYOUT() { return __MIDL_itf_searchapi_0000_0027_v0_0_c_ifspec$LAYOUT_; }

    static final VarHandle __MIDL_itf_searchapi_0000_0027_v0_0_c_ifspec$VH_ = MemoryHandles.asAddressVarHandle(__MIDL_itf_searchapi_0000_0027_v0_0_c_ifspec$LAYOUT_.varHandle(long.class));
    static final java.lang.invoke.VarHandle __MIDL_itf_searchapi_0000_0027_v0_0_c_ifspec$VH() { return __MIDL_itf_searchapi_0000_0027_v0_0_c_ifspec$VH_; }

    static final MemorySegment __MIDL_itf_searchapi_0000_0027_v0_0_c_ifspec$SEGMENT_ = RuntimeHelper.lookupGlobalVariable(LIBRARIES, "__MIDL_itf_searchapi_0000_0027_v0_0_c_ifspec", __MIDL_itf_searchapi_0000_0027_v0_0_c_ifspec$LAYOUT_);
    static final jdk.incubator.foreign.MemorySegment __MIDL_itf_searchapi_0000_0027_v0_0_c_ifspec$SEGMENT() { return __MIDL_itf_searchapi_0000_0027_v0_0_c_ifspec$SEGMENT_; }

    static final MemoryLayout __MIDL_itf_searchapi_0000_0027_v0_0_s_ifspec$LAYOUT_ = C_POINTER;
    static final jdk.incubator.foreign.MemoryLayout __MIDL_itf_searchapi_0000_0027_v0_0_s_ifspec$LAYOUT() { return __MIDL_itf_searchapi_0000_0027_v0_0_s_ifspec$LAYOUT_; }

    static final VarHandle __MIDL_itf_searchapi_0000_0027_v0_0_s_ifspec$VH_ = MemoryHandles.asAddressVarHandle(__MIDL_itf_searchapi_0000_0027_v0_0_s_ifspec$LAYOUT_.varHandle(long.class));
    static final java.lang.invoke.VarHandle __MIDL_itf_searchapi_0000_0027_v0_0_s_ifspec$VH() { return __MIDL_itf_searchapi_0000_0027_v0_0_s_ifspec$VH_; }

    static final MemorySegment __MIDL_itf_searchapi_0000_0027_v0_0_s_ifspec$SEGMENT_ = RuntimeHelper.lookupGlobalVariable(LIBRARIES, "__MIDL_itf_searchapi_0000_0027_v0_0_s_ifspec", __MIDL_itf_searchapi_0000_0027_v0_0_s_ifspec$LAYOUT_);
    static final jdk.incubator.foreign.MemorySegment __MIDL_itf_searchapi_0000_0027_v0_0_s_ifspec$SEGMENT() { return __MIDL_itf_searchapi_0000_0027_v0_0_s_ifspec$SEGMENT_; }

    static final MemoryLayout LIBID_SearchAPILib$LAYOUT_ = MemoryLayout.ofStruct(
        C_LONG.withName("Data1"),
        C_SHORT.withName("Data2"),
        C_SHORT.withName("Data3"),
        MemoryLayout.ofSequence(8, C_CHAR).withName("Data4")
    ).withName("_GUID");
    static final jdk.incubator.foreign.MemoryLayout LIBID_SearchAPILib$LAYOUT() { return LIBID_SearchAPILib$LAYOUT_; }

    static final MemorySegment LIBID_SearchAPILib$SEGMENT_ = RuntimeHelper.lookupGlobalVariable(LIBRARIES, "LIBID_SearchAPILib", LIBID_SearchAPILib$LAYOUT_);
    static final jdk.incubator.foreign.MemorySegment LIBID_SearchAPILib$SEGMENT() { return LIBID_SearchAPILib$SEGMENT_; }

    static final MemoryLayout CLSID_CSearchManager$LAYOUT_ = MemoryLayout.ofStruct(
        C_LONG.withName("Data1"),
        C_SHORT.withName("Data2"),
        C_SHORT.withName("Data3"),
        MemoryLayout.ofSequence(8, C_CHAR).withName("Data4")
    ).withName("_GUID");
    static final jdk.incubator.foreign.MemoryLayout CLSID_CSearchManager$LAYOUT() { return CLSID_CSearchManager$LAYOUT_; }

    static final MemorySegment CLSID_CSearchManager$SEGMENT_ = RuntimeHelper.lookupGlobalVariable(LIBRARIES, "CLSID_CSearchManager", CLSID_CSearchManager$LAYOUT_);
    static final jdk.incubator.foreign.MemorySegment CLSID_CSearchManager$SEGMENT() { return CLSID_CSearchManager$SEGMENT_; }

    static final MemoryLayout CLSID_CSearchRoot$LAYOUT_ = MemoryLayout.ofStruct(
        C_LONG.withName("Data1"),
        C_SHORT.withName("Data2"),
        C_SHORT.withName("Data3"),
        MemoryLayout.ofSequence(8, C_CHAR).withName("Data4")
    ).withName("_GUID");
    static final jdk.incubator.foreign.MemoryLayout CLSID_CSearchRoot$LAYOUT() { return CLSID_CSearchRoot$LAYOUT_; }

    static final MemorySegment CLSID_CSearchRoot$SEGMENT_ = RuntimeHelper.lookupGlobalVariable(LIBRARIES, "CLSID_CSearchRoot", CLSID_CSearchRoot$LAYOUT_);
    static final jdk.incubator.foreign.MemorySegment CLSID_CSearchRoot$SEGMENT() { return CLSID_CSearchRoot$SEGMENT_; }

    static final MemoryLayout CLSID_CSearchScopeRule$LAYOUT_ = MemoryLayout.ofStruct(
        C_LONG.withName("Data1"),
        C_SHORT.withName("Data2"),
        C_SHORT.withName("Data3"),
        MemoryLayout.ofSequence(8, C_CHAR).withName("Data4")
    ).withName("_GUID");
    static final jdk.incubator.foreign.MemoryLayout CLSID_CSearchScopeRule$LAYOUT() { return CLSID_CSearchScopeRule$LAYOUT_; }

    static final MemorySegment CLSID_CSearchScopeRule$SEGMENT_ = RuntimeHelper.lookupGlobalVariable(LIBRARIES, "CLSID_CSearchScopeRule", CLSID_CSearchScopeRule$LAYOUT_);
    static final jdk.incubator.foreign.MemorySegment CLSID_CSearchScopeRule$SEGMENT() { return CLSID_CSearchScopeRule$SEGMENT_; }

    static final MemoryLayout CLSID_FilterRegistration$LAYOUT_ = MemoryLayout.ofStruct(
        C_LONG.withName("Data1"),
        C_SHORT.withName("Data2"),
        C_SHORT.withName("Data3"),
        MemoryLayout.ofSequence(8, C_CHAR).withName("Data4")
    ).withName("_GUID");
    static final jdk.incubator.foreign.MemoryLayout CLSID_FilterRegistration$LAYOUT() { return CLSID_FilterRegistration$LAYOUT_; }

    static final MemorySegment CLSID_FilterRegistration$SEGMENT_ = RuntimeHelper.lookupGlobalVariable(LIBRARIES, "CLSID_FilterRegistration", CLSID_FilterRegistration$LAYOUT_);
    static final jdk.incubator.foreign.MemorySegment CLSID_FilterRegistration$SEGMENT() { return CLSID_FilterRegistration$SEGMENT_; }

    static final MemoryLayout __MIDL_itf_searchapi_0000_0028_v0_0_c_ifspec$LAYOUT_ = C_POINTER;
    static final jdk.incubator.foreign.MemoryLayout __MIDL_itf_searchapi_0000_0028_v0_0_c_ifspec$LAYOUT() { return __MIDL_itf_searchapi_0000_0028_v0_0_c_ifspec$LAYOUT_; }

    static final VarHandle __MIDL_itf_searchapi_0000_0028_v0_0_c_ifspec$VH_ = MemoryHandles.asAddressVarHandle(__MIDL_itf_searchapi_0000_0028_v0_0_c_ifspec$LAYOUT_.varHandle(long.class));
    static final java.lang.invoke.VarHandle __MIDL_itf_searchapi_0000_0028_v0_0_c_ifspec$VH() { return __MIDL_itf_searchapi_0000_0028_v0_0_c_ifspec$VH_; }

    static final MemorySegment __MIDL_itf_searchapi_0000_0028_v0_0_c_ifspec$SEGMENT_ = RuntimeHelper.lookupGlobalVariable(LIBRARIES, "__MIDL_itf_searchapi_0000_0028_v0_0_c_ifspec", __MIDL_itf_searchapi_0000_0028_v0_0_c_ifspec$LAYOUT_);
    static final jdk.incubator.foreign.MemorySegment __MIDL_itf_searchapi_0000_0028_v0_0_c_ifspec$SEGMENT() { return __MIDL_itf_searchapi_0000_0028_v0_0_c_ifspec$SEGMENT_; }

    static final MemoryLayout __MIDL_itf_searchapi_0000_0028_v0_0_s_ifspec$LAYOUT_ = C_POINTER;
    static final jdk.incubator.foreign.MemoryLayout __MIDL_itf_searchapi_0000_0028_v0_0_s_ifspec$LAYOUT() { return __MIDL_itf_searchapi_0000_0028_v0_0_s_ifspec$LAYOUT_; }

    static final VarHandle __MIDL_itf_searchapi_0000_0028_v0_0_s_ifspec$VH_ = MemoryHandles.asAddressVarHandle(__MIDL_itf_searchapi_0000_0028_v0_0_s_ifspec$LAYOUT_.varHandle(long.class));
    static final java.lang.invoke.VarHandle __MIDL_itf_searchapi_0000_0028_v0_0_s_ifspec$VH() { return __MIDL_itf_searchapi_0000_0028_v0_0_s_ifspec$VH_; }

    static final MemorySegment __MIDL_itf_searchapi_0000_0028_v0_0_s_ifspec$SEGMENT_ = RuntimeHelper.lookupGlobalVariable(LIBRARIES, "__MIDL_itf_searchapi_0000_0028_v0_0_s_ifspec", __MIDL_itf_searchapi_0000_0028_v0_0_s_ifspec$LAYOUT_);
    static final jdk.incubator.foreign.MemorySegment __MIDL_itf_searchapi_0000_0028_v0_0_s_ifspec$SEGMENT() { return __MIDL_itf_searchapi_0000_0028_v0_0_s_ifspec$SEGMENT_; }

    static final FunctionDescriptor BSTR_UserSize$FUNC_ = FunctionDescriptor.of(C_LONG,
        C_POINTER,
        C_LONG,
        C_POINTER
    );
    static final jdk.incubator.foreign.FunctionDescriptor BSTR_UserSize$FUNC() { return BSTR_UserSize$FUNC_; }

    static final MethodHandle BSTR_UserSize$MH_ = RuntimeHelper.downcallHandle(
        LIBRARIES, "BSTR_UserSize",
        "(Ljdk/incubator/foreign/MemoryAddress;ILjdk/incubator/foreign/MemoryAddress;)I",
        BSTR_UserSize$FUNC_, false
    );
    static final java.lang.invoke.MethodHandle BSTR_UserSize$MH() { return BSTR_UserSize$MH_; }

    static final FunctionDescriptor BSTR_UserMarshal$FUNC_ = FunctionDescriptor.of(C_POINTER,
        C_POINTER,
        C_POINTER,
        C_POINTER
    );
    static final jdk.incubator.foreign.FunctionDescriptor BSTR_UserMarshal$FUNC() { return BSTR_UserMarshal$FUNC_; }

    static final MethodHandle BSTR_UserMarshal$MH_ = RuntimeHelper.downcallHandle(
        LIBRARIES, "BSTR_UserMarshal",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)Ljdk/incubator/foreign/MemoryAddress;",
        BSTR_UserMarshal$FUNC_, false
    );
    static final java.lang.invoke.MethodHandle BSTR_UserMarshal$MH() { return BSTR_UserMarshal$MH_; }

    static final FunctionDescriptor BSTR_UserUnmarshal$FUNC_ = FunctionDescriptor.of(C_POINTER,
        C_POINTER,
        C_POINTER,
        C_POINTER
    );
    static final jdk.incubator.foreign.FunctionDescriptor BSTR_UserUnmarshal$FUNC() { return BSTR_UserUnmarshal$FUNC_; }

    static final MethodHandle BSTR_UserUnmarshal$MH_ = RuntimeHelper.downcallHandle(
        LIBRARIES, "BSTR_UserUnmarshal",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)Ljdk/incubator/foreign/MemoryAddress;",
        BSTR_UserUnmarshal$FUNC_, false
    );
    static final java.lang.invoke.MethodHandle BSTR_UserUnmarshal$MH() { return BSTR_UserUnmarshal$MH_; }

    static final FunctionDescriptor BSTR_UserFree$FUNC_ = FunctionDescriptor.ofVoid(
        C_POINTER,
        C_POINTER
    );
    static final jdk.incubator.foreign.FunctionDescriptor BSTR_UserFree$FUNC() { return BSTR_UserFree$FUNC_; }

    static final MethodHandle BSTR_UserFree$MH_ = RuntimeHelper.downcallHandle(
        LIBRARIES, "BSTR_UserFree",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)V",
        BSTR_UserFree$FUNC_, false
    );
    static final java.lang.invoke.MethodHandle BSTR_UserFree$MH() { return BSTR_UserFree$MH_; }

    static final FunctionDescriptor LPSAFEARRAY_UserSize$FUNC_ = FunctionDescriptor.of(C_LONG,
        C_POINTER,
        C_LONG,
        C_POINTER
    );
    static final jdk.incubator.foreign.FunctionDescriptor LPSAFEARRAY_UserSize$FUNC() { return LPSAFEARRAY_UserSize$FUNC_; }

    static final MethodHandle LPSAFEARRAY_UserSize$MH_ = RuntimeHelper.downcallHandle(
        LIBRARIES, "LPSAFEARRAY_UserSize",
        "(Ljdk/incubator/foreign/MemoryAddress;ILjdk/incubator/foreign/MemoryAddress;)I",
        LPSAFEARRAY_UserSize$FUNC_, false
    );
    static final java.lang.invoke.MethodHandle LPSAFEARRAY_UserSize$MH() { return LPSAFEARRAY_UserSize$MH_; }

    static final FunctionDescriptor LPSAFEARRAY_UserMarshal$FUNC_ = FunctionDescriptor.of(C_POINTER,
        C_POINTER,
        C_POINTER,
        C_POINTER
    );
    static final jdk.incubator.foreign.FunctionDescriptor LPSAFEARRAY_UserMarshal$FUNC() { return LPSAFEARRAY_UserMarshal$FUNC_; }

    static final MethodHandle LPSAFEARRAY_UserMarshal$MH_ = RuntimeHelper.downcallHandle(
        LIBRARIES, "LPSAFEARRAY_UserMarshal",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)Ljdk/incubator/foreign/MemoryAddress;",
        LPSAFEARRAY_UserMarshal$FUNC_, false
    );
    static final java.lang.invoke.MethodHandle LPSAFEARRAY_UserMarshal$MH() { return LPSAFEARRAY_UserMarshal$MH_; }

    static final FunctionDescriptor LPSAFEARRAY_UserUnmarshal$FUNC_ = FunctionDescriptor.of(C_POINTER,
        C_POINTER,
        C_POINTER,
        C_POINTER
    );
    static final jdk.incubator.foreign.FunctionDescriptor LPSAFEARRAY_UserUnmarshal$FUNC() { return LPSAFEARRAY_UserUnmarshal$FUNC_; }

    static final MethodHandle LPSAFEARRAY_UserUnmarshal$MH_ = RuntimeHelper.downcallHandle(
        LIBRARIES, "LPSAFEARRAY_UserUnmarshal",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)Ljdk/incubator/foreign/MemoryAddress;",
        LPSAFEARRAY_UserUnmarshal$FUNC_, false
    );
    static final java.lang.invoke.MethodHandle LPSAFEARRAY_UserUnmarshal$MH() { return LPSAFEARRAY_UserUnmarshal$MH_; }

    static final FunctionDescriptor LPSAFEARRAY_UserFree$FUNC_ = FunctionDescriptor.ofVoid(
        C_POINTER,
        C_POINTER
    );
    static final jdk.incubator.foreign.FunctionDescriptor LPSAFEARRAY_UserFree$FUNC() { return LPSAFEARRAY_UserFree$FUNC_; }

    static final MethodHandle LPSAFEARRAY_UserFree$MH_ = RuntimeHelper.downcallHandle(
        LIBRARIES, "LPSAFEARRAY_UserFree",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)V",
        LPSAFEARRAY_UserFree$FUNC_, false
    );
    static final java.lang.invoke.MethodHandle LPSAFEARRAY_UserFree$MH() { return LPSAFEARRAY_UserFree$MH_; }

    static final FunctionDescriptor BSTR_UserSize64$FUNC_ = FunctionDescriptor.of(C_LONG,
        C_POINTER,
        C_LONG,
        C_POINTER
    );
    static final jdk.incubator.foreign.FunctionDescriptor BSTR_UserSize64$FUNC() { return BSTR_UserSize64$FUNC_; }

    static final MethodHandle BSTR_UserSize64$MH_ = RuntimeHelper.downcallHandle(
        LIBRARIES, "BSTR_UserSize64",
        "(Ljdk/incubator/foreign/MemoryAddress;ILjdk/incubator/foreign/MemoryAddress;)I",
        BSTR_UserSize64$FUNC_, false
    );
    static final java.lang.invoke.MethodHandle BSTR_UserSize64$MH() { return BSTR_UserSize64$MH_; }

    static final FunctionDescriptor BSTR_UserMarshal64$FUNC_ = FunctionDescriptor.of(C_POINTER,
        C_POINTER,
        C_POINTER,
        C_POINTER
    );
    static final jdk.incubator.foreign.FunctionDescriptor BSTR_UserMarshal64$FUNC() { return BSTR_UserMarshal64$FUNC_; }

    static final MethodHandle BSTR_UserMarshal64$MH_ = RuntimeHelper.downcallHandle(
        LIBRARIES, "BSTR_UserMarshal64",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)Ljdk/incubator/foreign/MemoryAddress;",
        BSTR_UserMarshal64$FUNC_, false
    );
    static final java.lang.invoke.MethodHandle BSTR_UserMarshal64$MH() { return BSTR_UserMarshal64$MH_; }

    static final FunctionDescriptor BSTR_UserUnmarshal64$FUNC_ = FunctionDescriptor.of(C_POINTER,
        C_POINTER,
        C_POINTER,
        C_POINTER
    );
    static final jdk.incubator.foreign.FunctionDescriptor BSTR_UserUnmarshal64$FUNC() { return BSTR_UserUnmarshal64$FUNC_; }

    static final MethodHandle BSTR_UserUnmarshal64$MH_ = RuntimeHelper.downcallHandle(
        LIBRARIES, "BSTR_UserUnmarshal64",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)Ljdk/incubator/foreign/MemoryAddress;",
        BSTR_UserUnmarshal64$FUNC_, false
    );
    static final java.lang.invoke.MethodHandle BSTR_UserUnmarshal64$MH() { return BSTR_UserUnmarshal64$MH_; }

    static final FunctionDescriptor BSTR_UserFree64$FUNC_ = FunctionDescriptor.ofVoid(
        C_POINTER,
        C_POINTER
    );
    static final jdk.incubator.foreign.FunctionDescriptor BSTR_UserFree64$FUNC() { return BSTR_UserFree64$FUNC_; }

    static final MethodHandle BSTR_UserFree64$MH_ = RuntimeHelper.downcallHandle(
        LIBRARIES, "BSTR_UserFree64",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)V",
        BSTR_UserFree64$FUNC_, false
    );
    static final java.lang.invoke.MethodHandle BSTR_UserFree64$MH() { return BSTR_UserFree64$MH_; }

    static final FunctionDescriptor LPSAFEARRAY_UserSize64$FUNC_ = FunctionDescriptor.of(C_LONG,
        C_POINTER,
        C_LONG,
        C_POINTER
    );
    static final jdk.incubator.foreign.FunctionDescriptor LPSAFEARRAY_UserSize64$FUNC() { return LPSAFEARRAY_UserSize64$FUNC_; }

    static final MethodHandle LPSAFEARRAY_UserSize64$MH_ = RuntimeHelper.downcallHandle(
        LIBRARIES, "LPSAFEARRAY_UserSize64",
        "(Ljdk/incubator/foreign/MemoryAddress;ILjdk/incubator/foreign/MemoryAddress;)I",
        LPSAFEARRAY_UserSize64$FUNC_, false
    );
    static final java.lang.invoke.MethodHandle LPSAFEARRAY_UserSize64$MH() { return LPSAFEARRAY_UserSize64$MH_; }

    static final FunctionDescriptor LPSAFEARRAY_UserMarshal64$FUNC_ = FunctionDescriptor.of(C_POINTER,
        C_POINTER,
        C_POINTER,
        C_POINTER
    );
    static final jdk.incubator.foreign.FunctionDescriptor LPSAFEARRAY_UserMarshal64$FUNC() { return LPSAFEARRAY_UserMarshal64$FUNC_; }

    static final MethodHandle LPSAFEARRAY_UserMarshal64$MH_ = RuntimeHelper.downcallHandle(
        LIBRARIES, "LPSAFEARRAY_UserMarshal64",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)Ljdk/incubator/foreign/MemoryAddress;",
        LPSAFEARRAY_UserMarshal64$FUNC_, false
    );
    static final java.lang.invoke.MethodHandle LPSAFEARRAY_UserMarshal64$MH() { return LPSAFEARRAY_UserMarshal64$MH_; }

    static final FunctionDescriptor LPSAFEARRAY_UserUnmarshal64$FUNC_ = FunctionDescriptor.of(C_POINTER,
        C_POINTER,
        C_POINTER,
        C_POINTER
    );
    static final jdk.incubator.foreign.FunctionDescriptor LPSAFEARRAY_UserUnmarshal64$FUNC() { return LPSAFEARRAY_UserUnmarshal64$FUNC_; }

    static final MethodHandle LPSAFEARRAY_UserUnmarshal64$MH_ = RuntimeHelper.downcallHandle(
        LIBRARIES, "LPSAFEARRAY_UserUnmarshal64",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)Ljdk/incubator/foreign/MemoryAddress;",
        LPSAFEARRAY_UserUnmarshal64$FUNC_, false
    );
    static final java.lang.invoke.MethodHandle LPSAFEARRAY_UserUnmarshal64$MH() { return LPSAFEARRAY_UserUnmarshal64$MH_; }

    static final FunctionDescriptor LPSAFEARRAY_UserFree64$FUNC_ = FunctionDescriptor.ofVoid(
        C_POINTER,
        C_POINTER
    );
    static final jdk.incubator.foreign.FunctionDescriptor LPSAFEARRAY_UserFree64$FUNC() { return LPSAFEARRAY_UserFree64$FUNC_; }

    static final MethodHandle LPSAFEARRAY_UserFree64$MH_ = RuntimeHelper.downcallHandle(
        LIBRARIES, "LPSAFEARRAY_UserFree64",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)V",
        LPSAFEARRAY_UserFree64$FUNC_, false
    );
    static final java.lang.invoke.MethodHandle LPSAFEARRAY_UserFree64$MH() { return LPSAFEARRAY_UserFree64$MH_; }

    static final FunctionDescriptor ISearchCrawlScopeManager2_GetVersion_Proxy$FUNC_ = FunctionDescriptor.of(C_LONG,
        C_POINTER,
        C_POINTER,
        C_POINTER
    );
    static final jdk.incubator.foreign.FunctionDescriptor ISearchCrawlScopeManager2_GetVersion_Proxy$FUNC() { return ISearchCrawlScopeManager2_GetVersion_Proxy$FUNC_; }

    static final MethodHandle ISearchCrawlScopeManager2_GetVersion_Proxy$MH_ = RuntimeHelper.downcallHandle(
        LIBRARIES, "ISearchCrawlScopeManager2_GetVersion_Proxy",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)I",
        ISearchCrawlScopeManager2_GetVersion_Proxy$FUNC_, false
    );
    static final java.lang.invoke.MethodHandle ISearchCrawlScopeManager2_GetVersion_Proxy$MH() { return ISearchCrawlScopeManager2_GetVersion_Proxy$MH_; }

    static final FunctionDescriptor ISearchCrawlScopeManager2_GetVersion_Stub$FUNC_ = FunctionDescriptor.of(C_LONG,
        C_POINTER,
        C_POINTER
    );
    static final jdk.incubator.foreign.FunctionDescriptor ISearchCrawlScopeManager2_GetVersion_Stub$FUNC() { return ISearchCrawlScopeManager2_GetVersion_Stub$FUNC_; }

    static final MethodHandle ISearchCrawlScopeManager2_GetVersion_Stub$MH_ = RuntimeHelper.downcallHandle(
        LIBRARIES, "ISearchCrawlScopeManager2_GetVersion_Stub",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)I",
        ISearchCrawlScopeManager2_GetVersion_Stub$FUNC_, false
    );
    static final java.lang.invoke.MethodHandle ISearchCrawlScopeManager2_GetVersion_Stub$MH() { return ISearchCrawlScopeManager2_GetVersion_Stub$MH_; }

}

