// Generated by jextract

package com.github.tornaia.foreign.win.api.winnt.internal;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import jdk.incubator.foreign.*;
import jdk.incubator.foreign.MemoryLayout.PathElement;
import static jdk.incubator.foreign.CLinker.*;
class winnt_h$3 extends winnt_h$2 {

    /* package-private */ winnt_h$3() {}
    public static @C("int") int PROCESS_VM_WRITE() {
        return winnt_h$constants$13.PROCESS_VM_WRITE();
    }
    public static @C("int") int PROCESS_DUP_HANDLE() {
        return winnt_h$constants$13.PROCESS_DUP_HANDLE();
    }
    public static @C("int") int PROCESS_CREATE_PROCESS() {
        return winnt_h$constants$13.PROCESS_CREATE_PROCESS();
    }
    public static @C("int") int PROCESS_SET_QUOTA() {
        return winnt_h$constants$13.PROCESS_SET_QUOTA();
    }
    public static @C("int") int PROCESS_SET_INFORMATION() {
        return winnt_h$constants$13.PROCESS_SET_INFORMATION();
    }
    public static @C("int") int PROCESS_QUERY_INFORMATION() {
        return winnt_h$constants$13.PROCESS_QUERY_INFORMATION();
    }
    public static @C("int") int PROCESS_SUSPEND_RESUME() {
        return winnt_h$constants$13.PROCESS_SUSPEND_RESUME();
    }
    public static @C("int") int PROCESS_QUERY_LIMITED_INFORMATION() {
        return winnt_h$constants$13.PROCESS_QUERY_LIMITED_INFORMATION();
    }
    public static @C("int") int PROCESS_SET_LIMITED_INFORMATION() {
        return winnt_h$constants$13.PROCESS_SET_LIMITED_INFORMATION();
    }
    public static @C("long") int PROCESS_ALL_ACCESS() {
        return winnt_h$constants$13.PROCESS_ALL_ACCESS();
    }
    public static @C("int") int THREAD_TERMINATE() {
        return winnt_h$constants$13.THREAD_TERMINATE();
    }
    public static @C("int") int THREAD_SUSPEND_RESUME() {
        return winnt_h$constants$13.THREAD_SUSPEND_RESUME();
    }
    public static @C("int") int THREAD_GET_CONTEXT() {
        return winnt_h$constants$13.THREAD_GET_CONTEXT();
    }
    public static @C("int") int THREAD_SET_CONTEXT() {
        return winnt_h$constants$13.THREAD_SET_CONTEXT();
    }
    public static @C("int") int THREAD_QUERY_INFORMATION() {
        return winnt_h$constants$13.THREAD_QUERY_INFORMATION();
    }
    public static @C("int") int THREAD_SET_INFORMATION() {
        return winnt_h$constants$13.THREAD_SET_INFORMATION();
    }
    public static @C("int") int THREAD_SET_THREAD_TOKEN() {
        return winnt_h$constants$13.THREAD_SET_THREAD_TOKEN();
    }
    public static @C("int") int THREAD_IMPERSONATE() {
        return winnt_h$constants$13.THREAD_IMPERSONATE();
    }
    public static @C("int") int THREAD_DIRECT_IMPERSONATION() {
        return winnt_h$constants$13.THREAD_DIRECT_IMPERSONATION();
    }
    public static @C("int") int THREAD_SET_LIMITED_INFORMATION() {
        return winnt_h$constants$13.THREAD_SET_LIMITED_INFORMATION();
    }
    public static @C("int") int THREAD_QUERY_LIMITED_INFORMATION() {
        return winnt_h$constants$13.THREAD_QUERY_LIMITED_INFORMATION();
    }
    public static @C("int") int THREAD_RESUME() {
        return winnt_h$constants$13.THREAD_RESUME();
    }
    public static @C("long") int THREAD_ALL_ACCESS() {
        return winnt_h$constants$13.THREAD_ALL_ACCESS();
    }
    public static @C("int") int JOB_OBJECT_ASSIGN_PROCESS() {
        return winnt_h$constants$13.JOB_OBJECT_ASSIGN_PROCESS();
    }
    public static @C("int") int JOB_OBJECT_SET_ATTRIBUTES() {
        return winnt_h$constants$13.JOB_OBJECT_SET_ATTRIBUTES();
    }
    public static @C("int") int JOB_OBJECT_QUERY() {
        return winnt_h$constants$13.JOB_OBJECT_QUERY();
    }
    public static @C("int") int JOB_OBJECT_TERMINATE() {
        return winnt_h$constants$13.JOB_OBJECT_TERMINATE();
    }
    public static @C("int") int JOB_OBJECT_SET_SECURITY_ATTRIBUTES() {
        return winnt_h$constants$13.JOB_OBJECT_SET_SECURITY_ATTRIBUTES();
    }
    public static @C("int") int JOB_OBJECT_IMPERSONATE() {
        return winnt_h$constants$13.JOB_OBJECT_IMPERSONATE();
    }
    public static @C("long") int JOB_OBJECT_ALL_ACCESS() {
        return winnt_h$constants$13.JOB_OBJECT_ALL_ACCESS();
    }
    public static @C("int") int THREAD_BASE_PRIORITY_MIN() {
        return winnt_h$constants$13.THREAD_BASE_PRIORITY_MIN();
    }
    public static @C("int") int THREAD_BASE_PRIORITY_IDLE() {
        return winnt_h$constants$13.THREAD_BASE_PRIORITY_IDLE();
    }
    public static @C("int") int DYNAMIC_EH_CONTINUATION_TARGET_ADD() {
        return winnt_h$constants$13.DYNAMIC_EH_CONTINUATION_TARGET_ADD();
    }
    public static @C("int") int DYNAMIC_EH_CONTINUATION_TARGET_PROCESSED() {
        return winnt_h$constants$13.DYNAMIC_EH_CONTINUATION_TARGET_PROCESSED();
    }
    public static @C("unsigned long") int JOB_OBJECT_VALID_COMPLETION_FILTER() {
        return winnt_h$constants$13.JOB_OBJECT_VALID_COMPLETION_FILTER();
    }
    public static @C("int") int JOB_OBJECT_LIMIT_JOB_MEMORY_HIGH() {
        return winnt_h$constants$13.JOB_OBJECT_LIMIT_JOB_MEMORY_HIGH();
    }
    public static @C("int") int JOB_OBJECT_LIMIT_CPU_RATE_CONTROL() {
        return winnt_h$constants$13.JOB_OBJECT_LIMIT_CPU_RATE_CONTROL();
    }
    public static @C("int") int JOB_OBJECT_NOTIFICATION_LIMIT_VALID_FLAGS() {
        return winnt_h$constants$13.JOB_OBJECT_NOTIFICATION_LIMIT_VALID_FLAGS();
    }
    public static @C("long") int EVENT_ALL_ACCESS() {
        return winnt_h$constants$13.EVENT_ALL_ACCESS();
    }
    public static @C("long") int MUTANT_ALL_ACCESS() {
        return winnt_h$constants$13.MUTANT_ALL_ACCESS();
    }
    public static @C("long") int SEMAPHORE_ALL_ACCESS() {
        return winnt_h$constants$13.SEMAPHORE_ALL_ACCESS();
    }
    public static @C("long") int TIMER_ALL_ACCESS() {
        return winnt_h$constants$13.TIMER_ALL_ACCESS();
    }
    public static @C("int") int XSTATE_LEGACY_FLOATING_POINT() {
        return winnt_h$constants$13.XSTATE_LEGACY_FLOATING_POINT();
    }
    public static @C("int") int XSTATE_LEGACY_SSE() {
        return winnt_h$constants$13.XSTATE_LEGACY_SSE();
    }
    public static @C("int") int XSTATE_GSSE() {
        return winnt_h$constants$13.XSTATE_GSSE();
    }
    public static @C("int") int XSTATE_AVX() {
        return winnt_h$constants$13.XSTATE_AVX();
    }
    public static @C("int") int XSTATE_MPX_BNDREGS() {
        return winnt_h$constants$13.XSTATE_MPX_BNDREGS();
    }
    public static @C("int") int XSTATE_MPX_BNDCSR() {
        return winnt_h$constants$13.XSTATE_MPX_BNDCSR();
    }
    public static @C("int") int XSTATE_AVX512_KMASK() {
        return winnt_h$constants$13.XSTATE_AVX512_KMASK();
    }
    public static @C("int") int XSTATE_AVX512_ZMM_H() {
        return winnt_h$constants$13.XSTATE_AVX512_ZMM_H();
    }
    public static @C("int") int XSTATE_AVX512_ZMM() {
        return winnt_h$constants$13.XSTATE_AVX512_ZMM();
    }
    public static @C("int") int XSTATE_IPT() {
        return winnt_h$constants$13.XSTATE_IPT();
    }
    public static @C("int") int XSTATE_CET_U() {
        return winnt_h$constants$13.XSTATE_CET_U();
    }
    public static @C("int") int XSTATE_LWP() {
        return winnt_h$constants$13.XSTATE_LWP();
    }
    public static @C("int") int MAXIMUM_XSTATE_FEATURES() {
        return winnt_h$constants$13.MAXIMUM_XSTATE_FEATURES();
    }
    public static @C("unsigned long long") long XSTATE_MASK_LEGACY_FLOATING_POINT() {
        return winnt_h$constants$13.XSTATE_MASK_LEGACY_FLOATING_POINT();
    }
    public static @C("unsigned long long") long XSTATE_MASK_LEGACY_SSE() {
        return winnt_h$constants$13.XSTATE_MASK_LEGACY_SSE();
    }
    public static @C("unsigned long long") long XSTATE_MASK_LEGACY() {
        return winnt_h$constants$13.XSTATE_MASK_LEGACY();
    }
    public static @C("unsigned long long") long XSTATE_MASK_GSSE() {
        return winnt_h$constants$13.XSTATE_MASK_GSSE();
    }
    public static @C("unsigned long long") long XSTATE_MASK_AVX() {
        return winnt_h$constants$13.XSTATE_MASK_AVX();
    }
    public static @C("unsigned long long") long XSTATE_MASK_MPX() {
        return winnt_h$constants$13.XSTATE_MASK_MPX();
    }
    public static @C("unsigned long long") long XSTATE_MASK_AVX512() {
        return winnt_h$constants$13.XSTATE_MASK_AVX512();
    }
    public static @C("unsigned long long") long XSTATE_MASK_IPT() {
        return winnt_h$constants$13.XSTATE_MASK_IPT();
    }
    public static @C("unsigned long long") long XSTATE_MASK_CET_U() {
        return winnt_h$constants$13.XSTATE_MASK_CET_U();
    }
    public static @C("unsigned long long") long XSTATE_MASK_LWP() {
        return winnt_h$constants$13.XSTATE_MASK_LWP();
    }
    public static @C("unsigned long long") long XSTATE_MASK_ALLOWED() {
        return winnt_h$constants$13.XSTATE_MASK_ALLOWED();
    }
    public static @C("unsigned long long") long XSTATE_MASK_PERSISTENT() {
        return winnt_h$constants$13.XSTATE_MASK_PERSISTENT();
    }
    public static @C("unsigned long long") long XSTATE_MASK_USER_VISIBLE_SUPERVISOR() {
        return winnt_h$constants$13.XSTATE_MASK_USER_VISIBLE_SUPERVISOR();
    }
    public static @C("int") int XSTATE_COMPACTION_ENABLE() {
        return winnt_h$constants$13.XSTATE_COMPACTION_ENABLE();
    }
    public static @C("unsigned long long") long XSTATE_COMPACTION_ENABLE_MASK() {
        return winnt_h$constants$13.XSTATE_COMPACTION_ENABLE_MASK();
    }
    public static @C("int") int XSTATE_ALIGN_BIT() {
        return winnt_h$constants$13.XSTATE_ALIGN_BIT();
    }
    public static @C("unsigned long long") long XSTATE_ALIGN_MASK() {
        return winnt_h$constants$13.XSTATE_ALIGN_MASK();
    }
    public static @C("int") int XSTATE_CONTROLFLAG_XSAVEOPT_MASK() {
        return winnt_h$constants$13.XSTATE_CONTROLFLAG_XSAVEOPT_MASK();
    }
    public static @C("int") int XSTATE_CONTROLFLAG_XSAVEC_MASK() {
        return winnt_h$constants$13.XSTATE_CONTROLFLAG_XSAVEC_MASK();
    }
    public static @C("int") int XSTATE_CONTROLFLAG_VALID_MASK() {
        return winnt_h$constants$13.XSTATE_CONTROLFLAG_VALID_MASK();
    }
    public static @C("int") int CFG_CALL_TARGET_VALID() {
        return winnt_h$constants$13.CFG_CALL_TARGET_VALID();
    }
    public static @C("int") int CFG_CALL_TARGET_PROCESSED() {
        return winnt_h$constants$13.CFG_CALL_TARGET_PROCESSED();
    }
    public static @C("int") int CFG_CALL_TARGET_CONVERT_EXPORT_SUPPRESSED_TO_VALID() {
        return winnt_h$constants$13.CFG_CALL_TARGET_CONVERT_EXPORT_SUPPRESSED_TO_VALID();
    }
    public static @C("long") int SECTION_ALL_ACCESS() {
        return winnt_h$constants$13.SECTION_ALL_ACCESS();
    }
    public static @C("long") int SESSION_ALL_ACCESS() {
        return winnt_h$constants$13.SESSION_ALL_ACCESS();
    }
    public static @C("unsigned int") int PAGE_ENCLAVE_THREAD_CONTROL() {
        return winnt_h$constants$13.PAGE_ENCLAVE_THREAD_CONTROL();
    }
    public static @C("unsigned int") int PAGE_REVERT_TO_FILE_MAP() {
        return winnt_h$constants$13.PAGE_REVERT_TO_FILE_MAP();
    }
    public static @C("int") int PAGE_ENCLAVE_DECOMMIT() {
        return winnt_h$constants$13.PAGE_ENCLAVE_DECOMMIT();
    }
    public static @C("int") int PAGE_ENCLAVE_SS_FIRST() {
        return winnt_h$constants$13.PAGE_ENCLAVE_SS_FIRST();
    }
    public static @C("int") int PAGE_ENCLAVE_SS_REST() {
        return winnt_h$constants$13.PAGE_ENCLAVE_SS_REST();
    }
    public static @C("unsigned int") int MEM_4MB_PAGES() {
        return winnt_h$constants$13.MEM_4MB_PAGES();
    }
    public static @C("int") int MEM_64K_PAGES() {
        return winnt_h$constants$13.MEM_64K_PAGES();
    }
    public static @C("long long") long MEM_EXTENDED_PARAMETER_NUMA_NODE_MANDATORY() {
        return winnt_h$constants$13.MEM_EXTENDED_PARAMETER_NUMA_NODE_MANDATORY();
    }
    public static @C("unsigned int") int SEC_LARGE_PAGES() {
        return winnt_h$constants$13.SEC_LARGE_PAGES();
    }
    public static @C("int") int SEC_IMAGE_NO_EXECUTE() {
        return winnt_h$constants$13.SEC_IMAGE_NO_EXECUTE();
    }
    public static @C("int") int FILE_READ_DATA() {
        return winnt_h$constants$13.FILE_READ_DATA();
    }
    public static @C("int") int FILE_LIST_DIRECTORY() {
        return winnt_h$constants$13.FILE_LIST_DIRECTORY();
    }
    public static @C("int") int FILE_WRITE_DATA() {
        return winnt_h$constants$13.FILE_WRITE_DATA();
    }
    public static @C("int") int FILE_ADD_FILE() {
        return winnt_h$constants$13.FILE_ADD_FILE();
    }
    public static @C("int") int FILE_APPEND_DATA() {
        return winnt_h$constants$13.FILE_APPEND_DATA();
    }
    public static @C("int") int FILE_ADD_SUBDIRECTORY() {
        return winnt_h$constants$13.FILE_ADD_SUBDIRECTORY();
    }
    public static @C("int") int FILE_CREATE_PIPE_INSTANCE() {
        return winnt_h$constants$13.FILE_CREATE_PIPE_INSTANCE();
    }
    public static @C("int") int FILE_READ_EA() {
        return winnt_h$constants$13.FILE_READ_EA();
    }
    public static @C("int") int FILE_WRITE_EA() {
        return winnt_h$constants$13.FILE_WRITE_EA();
    }
    public static @C("int") int FILE_EXECUTE() {
        return winnt_h$constants$13.FILE_EXECUTE();
    }
    public static @C("int") int FILE_TRAVERSE() {
        return winnt_h$constants$13.FILE_TRAVERSE();
    }
    public static @C("int") int FILE_DELETE_CHILD() {
        return winnt_h$constants$13.FILE_DELETE_CHILD();
    }
    public static @C("int") int FILE_READ_ATTRIBUTES() {
        return winnt_h$constants$13.FILE_READ_ATTRIBUTES();
    }
    public static @C("int") int FILE_WRITE_ATTRIBUTES() {
        return winnt_h$constants$13.FILE_WRITE_ATTRIBUTES();
    }
    public static @C("long") int FILE_ALL_ACCESS() {
        return winnt_h$constants$13.FILE_ALL_ACCESS();
    }
    public static @C("long") int FILE_GENERIC_READ() {
        return winnt_h$constants$13.FILE_GENERIC_READ();
    }
    public static @C("long") int FILE_GENERIC_WRITE() {
        return winnt_h$constants$13.FILE_GENERIC_WRITE();
    }
    public static @C("long") int FILE_GENERIC_EXECUTE() {
        return winnt_h$constants$13.FILE_GENERIC_EXECUTE();
    }
    public static @C("unsigned long") int MAILSLOT_NO_MESSAGE() {
        return winnt_h$constants$13.MAILSLOT_NO_MESSAGE();
    }
    public static @C("unsigned long") int MAILSLOT_WAIT_FOREVER() {
        return winnt_h$constants$13.MAILSLOT_WAIT_FOREVER();
    }
    public static @C("long long") long FILE_INVALID_FILE_ID() {
        return winnt_h$constants$13.FILE_INVALID_FILE_ID();
    }
    public static @C("unsigned long") int REPARSE_GUID_DATA_BUFFER_HEADER_SIZE() {
        return winnt_h$constants$13.REPARSE_GUID_DATA_BUFFER_HEADER_SIZE();
    }
    public static @C("int") int MAXIMUM_REPARSE_DATA_BUFFER_SIZE() {
        return winnt_h$constants$13.MAXIMUM_REPARSE_DATA_BUFFER_SIZE();
    }
    public static @C("int") int IO_REPARSE_TAG_RESERVED_ZERO() {
        return winnt_h$constants$13.IO_REPARSE_TAG_RESERVED_ZERO();
    }
    public static @C("int") int IO_REPARSE_TAG_RESERVED_ONE() {
        return winnt_h$constants$13.IO_REPARSE_TAG_RESERVED_ONE();
    }
    public static @C("int") int IO_REPARSE_TAG_RESERVED_TWO() {
        return winnt_h$constants$13.IO_REPARSE_TAG_RESERVED_TWO();
    }
    public static @C("int") int IO_REPARSE_TAG_RESERVED_RANGE() {
        return winnt_h$constants$13.IO_REPARSE_TAG_RESERVED_RANGE();
    }
    public static @C("unsigned long") int IO_REPARSE_TAG_MOUNT_POINT() {
        return winnt_h$constants$13.IO_REPARSE_TAG_MOUNT_POINT();
    }
    public static @C("unsigned long") int IO_REPARSE_TAG_HSM() {
        return winnt_h$constants$13.IO_REPARSE_TAG_HSM();
    }
    public static @C("unsigned long") int IO_REPARSE_TAG_HSM2() {
        return winnt_h$constants$13.IO_REPARSE_TAG_HSM2();
    }
    public static @C("unsigned long") int IO_REPARSE_TAG_SIS() {
        return winnt_h$constants$13.IO_REPARSE_TAG_SIS();
    }
    public static @C("unsigned long") int IO_REPARSE_TAG_WIM() {
        return winnt_h$constants$13.IO_REPARSE_TAG_WIM();
    }
    public static @C("unsigned long") int IO_REPARSE_TAG_CSV() {
        return winnt_h$constants$13.IO_REPARSE_TAG_CSV();
    }
    public static @C("unsigned long") int IO_REPARSE_TAG_DFS() {
        return winnt_h$constants$13.IO_REPARSE_TAG_DFS();
    }
    public static @C("unsigned long") int IO_REPARSE_TAG_SYMLINK() {
        return winnt_h$constants$13.IO_REPARSE_TAG_SYMLINK();
    }
    public static @C("unsigned long") int IO_REPARSE_TAG_DFSR() {
        return winnt_h$constants$13.IO_REPARSE_TAG_DFSR();
    }
    public static @C("unsigned long") int IO_REPARSE_TAG_DEDUP() {
        return winnt_h$constants$13.IO_REPARSE_TAG_DEDUP();
    }
    public static @C("unsigned long") int IO_REPARSE_TAG_NFS() {
        return winnt_h$constants$13.IO_REPARSE_TAG_NFS();
    }
    public static @C("unsigned long") int IO_REPARSE_TAG_FILE_PLACEHOLDER() {
        return winnt_h$constants$13.IO_REPARSE_TAG_FILE_PLACEHOLDER();
    }
    public static @C("unsigned long") int IO_REPARSE_TAG_WOF() {
        return winnt_h$constants$13.IO_REPARSE_TAG_WOF();
    }
    public static @C("unsigned long") int IO_REPARSE_TAG_WCI() {
        return winnt_h$constants$13.IO_REPARSE_TAG_WCI();
    }
    public static @C("unsigned long") int IO_REPARSE_TAG_WCI_1() {
        return winnt_h$constants$13.IO_REPARSE_TAG_WCI_1();
    }
    public static @C("unsigned long") int IO_REPARSE_TAG_GLOBAL_REPARSE() {
        return winnt_h$constants$13.IO_REPARSE_TAG_GLOBAL_REPARSE();
    }
    public static @C("unsigned long") int IO_REPARSE_TAG_CLOUD() {
        return winnt_h$constants$13.IO_REPARSE_TAG_CLOUD();
    }
    public static @C("unsigned long") int IO_REPARSE_TAG_CLOUD_1() {
        return winnt_h$constants$13.IO_REPARSE_TAG_CLOUD_1();
    }
    public static @C("unsigned long") int IO_REPARSE_TAG_CLOUD_2() {
        return winnt_h$constants$13.IO_REPARSE_TAG_CLOUD_2();
    }
    public static @C("unsigned long") int IO_REPARSE_TAG_CLOUD_3() {
        return winnt_h$constants$13.IO_REPARSE_TAG_CLOUD_3();
    }
    public static @C("unsigned long") int IO_REPARSE_TAG_CLOUD_4() {
        return winnt_h$constants$13.IO_REPARSE_TAG_CLOUD_4();
    }
    public static @C("unsigned long") int IO_REPARSE_TAG_CLOUD_5() {
        return winnt_h$constants$13.IO_REPARSE_TAG_CLOUD_5();
    }
    public static @C("unsigned long") int IO_REPARSE_TAG_CLOUD_6() {
        return winnt_h$constants$13.IO_REPARSE_TAG_CLOUD_6();
    }
    public static @C("unsigned long") int IO_REPARSE_TAG_CLOUD_7() {
        return winnt_h$constants$13.IO_REPARSE_TAG_CLOUD_7();
    }
    public static @C("unsigned long") int IO_REPARSE_TAG_CLOUD_8() {
        return winnt_h$constants$13.IO_REPARSE_TAG_CLOUD_8();
    }
    public static @C("unsigned long") int IO_REPARSE_TAG_CLOUD_9() {
        return winnt_h$constants$13.IO_REPARSE_TAG_CLOUD_9();
    }
    public static @C("unsigned long") int IO_REPARSE_TAG_CLOUD_A() {
        return winnt_h$constants$13.IO_REPARSE_TAG_CLOUD_A();
    }
    public static @C("unsigned long") int IO_REPARSE_TAG_CLOUD_B() {
        return winnt_h$constants$13.IO_REPARSE_TAG_CLOUD_B();
    }
    public static @C("unsigned long") int IO_REPARSE_TAG_CLOUD_C() {
        return winnt_h$constants$13.IO_REPARSE_TAG_CLOUD_C();
    }
    public static @C("unsigned long") int IO_REPARSE_TAG_CLOUD_D() {
        return winnt_h$constants$13.IO_REPARSE_TAG_CLOUD_D();
    }
    public static @C("unsigned long") int IO_REPARSE_TAG_CLOUD_E() {
        return winnt_h$constants$13.IO_REPARSE_TAG_CLOUD_E();
    }
    public static @C("unsigned long") int IO_REPARSE_TAG_CLOUD_F() {
        return winnt_h$constants$13.IO_REPARSE_TAG_CLOUD_F();
    }
    public static @C("long") int IO_REPARSE_TAG_CLOUD_MASK() {
        return winnt_h$constants$13.IO_REPARSE_TAG_CLOUD_MASK();
    }
    public static @C("unsigned long") int IO_REPARSE_TAG_APPEXECLINK() {
        return winnt_h$constants$13.IO_REPARSE_TAG_APPEXECLINK();
    }
    public static @C("unsigned long") int IO_REPARSE_TAG_PROJFS() {
        return winnt_h$constants$13.IO_REPARSE_TAG_PROJFS();
    }
    public static @C("unsigned long") int IO_REPARSE_TAG_STORAGE_SYNC() {
        return winnt_h$constants$13.IO_REPARSE_TAG_STORAGE_SYNC();
    }
    public static @C("unsigned long") int IO_REPARSE_TAG_WCI_TOMBSTONE() {
        return winnt_h$constants$13.IO_REPARSE_TAG_WCI_TOMBSTONE();
    }
    public static @C("unsigned long") int IO_REPARSE_TAG_UNHANDLED() {
        return winnt_h$constants$13.IO_REPARSE_TAG_UNHANDLED();
    }
    public static @C("unsigned long") int IO_REPARSE_TAG_ONEDRIVE() {
        return winnt_h$constants$13.IO_REPARSE_TAG_ONEDRIVE();
    }
    public static @C("unsigned long") int IO_REPARSE_TAG_PROJFS_TOMBSTONE() {
        return winnt_h$constants$13.IO_REPARSE_TAG_PROJFS_TOMBSTONE();
    }
    public static @C("unsigned long") int IO_REPARSE_TAG_AF_UNIX() {
        return winnt_h$constants$13.IO_REPARSE_TAG_AF_UNIX();
    }
    public static @C("unsigned long") int IO_REPARSE_TAG_WCI_LINK() {
        return winnt_h$constants$13.IO_REPARSE_TAG_WCI_LINK();
    }
    public static @C("unsigned long") int IO_REPARSE_TAG_WCI_LINK_1() {
        return winnt_h$constants$13.IO_REPARSE_TAG_WCI_LINK_1();
    }
    public static @C("int") int SHUFFLE_FILE_FLAG_SKIP_INITIALIZING_NEW_CLUSTERS() {
        return winnt_h$constants$13.SHUFFLE_FILE_FLAG_SKIP_INITIALIZING_NEW_CLUSTERS();
    }
    public static @C("long") int IO_COMPLETION_ALL_ACCESS() {
        return winnt_h$constants$13.IO_COMPLETION_ALL_ACCESS();
    }
    public static @C("unsigned long long") long IO_QOS_MAX_RESERVATION() {
        return winnt_h$constants$13.IO_QOS_MAX_RESERVATION();
    }
    public static @C("char*") MemorySegment SMB_CCF_APP_INSTANCE_EA_NAME() {
        return winnt_h$constants$13.SMB_CCF_APP_INSTANCE_EA_NAME();
    }
    public static @C("int") int PERFSTATE_POLICY_CHANGE_DECREASE_MAX() {
        return winnt_h$constants$13.PERFSTATE_POLICY_CHANGE_DECREASE_MAX();
    }
    public static @C("int") int PERFSTATE_POLICY_CHANGE_INCREASE_MAX() {
        return winnt_h$constants$13.PERFSTATE_POLICY_CHANGE_INCREASE_MAX();
    }
    public static @C("int") int PROCESSOR_PERF_BOOST_MODE_MAX() {
        return winnt_h$constants$13.PROCESSOR_PERF_BOOST_MODE_MAX();
    }
    public static @C("int") int CORE_PARKING_POLICY_CHANGE_MAX() {
        return winnt_h$constants$13.CORE_PARKING_POLICY_CHANGE_MAX();
    }
    public static @C("unsigned long") int ES_SYSTEM_REQUIRED() {
        return winnt_h$constants$13.ES_SYSTEM_REQUIRED();
    }
    public static @C("unsigned long") int ES_DISPLAY_REQUIRED() {
        return winnt_h$constants$13.ES_DISPLAY_REQUIRED();
    }
    public static @C("unsigned long") int ES_USER_PRESENT() {
        return winnt_h$constants$13.ES_USER_PRESENT();
    }
    public static @C("unsigned long") int ES_AWAYMODE_REQUIRED() {
        return winnt_h$constants$13.ES_AWAYMODE_REQUIRED();
    }
    public static @C("unsigned long") int ES_CONTINUOUS() {
        return winnt_h$constants$13.ES_CONTINUOUS();
    }
    public static @C("unsigned int") int DIAGNOSTIC_REASON_NOT_SPECIFIED() {
        return winnt_h$constants$13.DIAGNOSTIC_REASON_NOT_SPECIFIED();
    }
    public static @C("unsigned int") int DIAGNOSTIC_REASON_INVALID_FLAGS() {
        return winnt_h$constants$13.DIAGNOSTIC_REASON_INVALID_FLAGS();
    }
    public static @C("int") int POWER_REQUEST_CONTEXT_VERSION() {
        return winnt_h$constants$13.POWER_REQUEST_CONTEXT_VERSION();
    }
    public static @C("int") int POWER_REQUEST_CONTEXT_SIMPLE_STRING() {
        return winnt_h$constants$13.POWER_REQUEST_CONTEXT_SIMPLE_STRING();
    }
    public static @C("int") int POWER_REQUEST_CONTEXT_DETAILED_STRING() {
        return winnt_h$constants$13.POWER_REQUEST_CONTEXT_DETAILED_STRING();
    }
    public static @C("int") int POWER_SETTING_VALUE_VERSION() {
        return winnt_h$constants$13.POWER_SETTING_VALUE_VERSION();
    }
    public static @C("int") int POWER_PLATFORM_ROLE_V1() {
        return winnt_h$constants$13.POWER_PLATFORM_ROLE_V1();
    }
    public static @C("int") int POWER_PLATFORM_ROLE_V1_MAX() {
        return winnt_h$constants$13.POWER_PLATFORM_ROLE_V1_MAX();
    }
    public static @C("int") int POWER_PLATFORM_ROLE_V2() {
        return winnt_h$constants$13.POWER_PLATFORM_ROLE_V2();
    }
    public static @C("int") int POWER_PLATFORM_ROLE_V2_MAX() {
        return winnt_h$constants$13.POWER_PLATFORM_ROLE_V2_MAX();
    }
    public static @C("int") int POWER_PLATFORM_ROLE_VERSION() {
        return winnt_h$constants$13.POWER_PLATFORM_ROLE_VERSION();
    }
    public static @C("int") int POWER_PLATFORM_ROLE_VERSION_MAX() {
        return winnt_h$constants$13.POWER_PLATFORM_ROLE_VERSION_MAX();
    }
    public static @C("unsigned int") int POWER_ACTION_CRITICAL() {
        return winnt_h$constants$13.POWER_ACTION_CRITICAL();
    }
    public static @C("unsigned int") int POWER_FORCE_TRIGGER_RESET() {
        return winnt_h$constants$13.POWER_FORCE_TRIGGER_RESET();
    }
    public static @C("unsigned int") int BATTERY_DISCHARGE_FLAGS_ENABLE() {
        return winnt_h$constants$13.BATTERY_DISCHARGE_FLAGS_ENABLE();
    }
    public static @C("int") int IMAGE_FILE_MACHINE_AXP64() {
        return winnt_h$constants$13.IMAGE_FILE_MACHINE_AXP64();
    }
    public static @C("int") int IMAGE_NT_OPTIONAL_HDR_MAGIC() {
        return winnt_h$constants$13.IMAGE_NT_OPTIONAL_HDR_MAGIC();
    }
    public static @C("unsigned int") int IMAGE_SCN_MEM_WRITE() {
        return winnt_h$constants$13.IMAGE_SCN_MEM_WRITE();
    }
    public static @C("short") short IMAGE_SYM_UNDEFINED() {
        return winnt_h$constants$13.IMAGE_SYM_UNDEFINED();
    }
    public static @C("short") short IMAGE_SYM_ABSOLUTE() {
        return winnt_h$constants$13.IMAGE_SYM_ABSOLUTE();
    }
    public static @C("short") short IMAGE_SYM_DEBUG() {
        return winnt_h$constants$13.IMAGE_SYM_DEBUG();
    }
    public static @C("int") int IMAGE_SYM_SECTION_MAX_EX() {
        return winnt_h$constants$13.IMAGE_SYM_SECTION_MAX_EX();
    }
    public static @C("unsigned char") byte IMAGE_SYM_CLASS_END_OF_FUNCTION() {
        return winnt_h$constants$13.IMAGE_SYM_CLASS_END_OF_FUNCTION();
    }
    public static @C("char*") MemorySegment IMAGE_ARCHIVE_START() {
        return winnt_h$constants$13.IMAGE_ARCHIVE_START();
    }
    public static @C("char*") MemorySegment IMAGE_ARCHIVE_END() {
        return winnt_h$constants$13.IMAGE_ARCHIVE_END();
    }
    public static @C("char*") MemorySegment IMAGE_ARCHIVE_PAD() {
        return winnt_h$constants$13.IMAGE_ARCHIVE_PAD();
    }
    public static @C("char*") MemorySegment IMAGE_ARCHIVE_LINKER_MEMBER() {
        return winnt_h$constants$13.IMAGE_ARCHIVE_LINKER_MEMBER();
    }
    public static @C("char*") MemorySegment IMAGE_ARCHIVE_LONGNAMES_MEMBER() {
        return winnt_h$constants$13.IMAGE_ARCHIVE_LONGNAMES_MEMBER();
    }
    public static @C("char*") MemorySegment IMAGE_ARCHIVE_HYBRIDMAP_MEMBER() {
        return winnt_h$constants$13.IMAGE_ARCHIVE_HYBRIDMAP_MEMBER();
    }
    public static @C("unsigned long long") long IMAGE_ORDINAL_FLAG64() {
        return winnt_h$constants$13.IMAGE_ORDINAL_FLAG64();
    }
    public static @C("unsigned int") int IMAGE_ORDINAL_FLAG32() {
        return winnt_h$constants$13.IMAGE_ORDINAL_FLAG32();
    }
    public static @C("unsigned long long") long IMAGE_ORDINAL_FLAG() {
        return winnt_h$constants$13.IMAGE_ORDINAL_FLAG();
    }
    public static @C("unsigned int") int IMAGE_RESOURCE_NAME_IS_STRING() {
        return winnt_h$constants$13.IMAGE_RESOURCE_NAME_IS_STRING();
    }
    public static @C("unsigned int") int IMAGE_RESOURCE_DATA_IS_DIRECTORY() {
        return winnt_h$constants$13.IMAGE_RESOURCE_DATA_IS_DIRECTORY();
    }
    public static @C("unsigned int") int IMAGE_HOT_PATCH_CHUNK_INVERSE() {
        return winnt_h$constants$13.IMAGE_HOT_PATCH_CHUNK_INVERSE();
    }
    public static @C("unsigned int") int IMAGE_GUARD_CF_FUNCTION_TABLE_SIZE_MASK() {
        return winnt_h$constants$13.IMAGE_GUARD_CF_FUNCTION_TABLE_SIZE_MASK();
    }
    public static @C("int") int IMAGE_ENCLAVE_LONG_ID_LENGTH() {
        return winnt_h$constants$13.IMAGE_ENCLAVE_LONG_ID_LENGTH();
    }
    public static @C("int") int IMAGE_ENCLAVE_SHORT_ID_LENGTH() {
        return winnt_h$constants$13.IMAGE_ENCLAVE_SHORT_ID_LENGTH();
    }
    public static @C("long") int IMAGE_ENCLAVE_MINIMUM_CONFIG_SIZE() {
        return winnt_h$constants$13.IMAGE_ENCLAVE_MINIMUM_CONFIG_SIZE();
    }
    public static @C("unsigned long") int RTL_RUN_ONCE_CHECK_ONLY() {
        return winnt_h$constants$13.RTL_RUN_ONCE_CHECK_ONLY();
    }
    public static @C("unsigned long") int RTL_RUN_ONCE_ASYNC() {
        return winnt_h$constants$13.RTL_RUN_ONCE_ASYNC();
    }
    public static @C("unsigned long") int RTL_RUN_ONCE_INIT_FAILED() {
        return winnt_h$constants$13.RTL_RUN_ONCE_INIT_FAILED();
    }
    public static @C("unsigned int") int FAST_FAIL_INVALID_FAST_FAIL_CODE() {
        return winnt_h$constants$13.FAST_FAIL_INVALID_FAST_FAIL_CODE();
    }
    public static @C("int") int COMPRESSION_FORMAT_NONE() {
        return winnt_h$constants$13.COMPRESSION_FORMAT_NONE();
    }
    public static @C("int") int COMPRESSION_FORMAT_DEFAULT() {
        return winnt_h$constants$13.COMPRESSION_FORMAT_DEFAULT();
    }
    public static @C("int") int COMPRESSION_FORMAT_LZNT1() {
        return winnt_h$constants$13.COMPRESSION_FORMAT_LZNT1();
    }
    public static @C("int") int COMPRESSION_FORMAT_XPRESS() {
        return winnt_h$constants$13.COMPRESSION_FORMAT_XPRESS();
    }
    public static @C("int") int COMPRESSION_FORMAT_XPRESS_HUFF() {
        return winnt_h$constants$13.COMPRESSION_FORMAT_XPRESS_HUFF();
    }
    public static @C("int") int COMPRESSION_ENGINE_STANDARD() {
        return winnt_h$constants$13.COMPRESSION_ENGINE_STANDARD();
    }
    public static @C("int") int COMPRESSION_ENGINE_MAXIMUM() {
        return winnt_h$constants$13.COMPRESSION_ENGINE_MAXIMUM();
    }
    public static @C("int") int COMPRESSION_ENGINE_HIBER() {
        return winnt_h$constants$13.COMPRESSION_ENGINE_HIBER();
    }
    public static @C("int") int SEF_MACL_VALID_FLAGS() {
        return winnt_h$constants$13.SEF_MACL_VALID_FLAGS();
    }
    public static @C("int") int RTL_UMS_VERSION() {
        return winnt_h$constants$13.RTL_UMS_VERSION();
    }
    public static @C("int") int VRL_PREDEFINED_CLASS_BEGIN() {
        return winnt_h$constants$13.VRL_PREDEFINED_CLASS_BEGIN();
    }
    public static @C("int") int VRL_CUSTOM_CLASS_BEGIN() {
        return winnt_h$constants$13.VRL_CUSTOM_CLASS_BEGIN();
    }
    public static @C("int") int VRL_CLASS_CONSISTENCY() {
        return winnt_h$constants$13.VRL_CLASS_CONSISTENCY();
    }
    public static @C("int") int VRL_ENABLE_KERNEL_BREAKS() {
        return winnt_h$constants$13.VRL_ENABLE_KERNEL_BREAKS();
    }
    public static @C("unsigned long") int CTMF_INCLUDE_APPCONTAINER() {
        return winnt_h$constants$13.CTMF_INCLUDE_APPCONTAINER();
    }
    public static @C("unsigned long") int CTMF_INCLUDE_LPAC() {
        return winnt_h$constants$13.CTMF_INCLUDE_LPAC();
    }
    public static @C("unsigned long") int CTMF_VALID_FLAGS() {
        return winnt_h$constants$13.CTMF_VALID_FLAGS();
    }
    public static @C("int") int FLUSH_NV_MEMORY_IN_FLAG_NO_DRAIN() {
        return winnt_h$constants$13.FLUSH_NV_MEMORY_IN_FLAG_NO_DRAIN();
    }
    public static @C("unsigned long long") long FLUSH_NV_MEMORY_DEFAULT_TOKEN() {
        return winnt_h$constants$13.FLUSH_NV_MEMORY_DEFAULT_TOKEN();
    }
    public static @C("int") int WRITE_NV_MEMORY_FLAG_FLUSH() {
        return winnt_h$constants$13.WRITE_NV_MEMORY_FLAG_FLUSH();
    }
    public static @C("int") int WRITE_NV_MEMORY_FLAG_NON_TEMPORAL() {
        return winnt_h$constants$13.WRITE_NV_MEMORY_FLAG_NON_TEMPORAL();
    }
    public static @C("int") int WRITE_NV_MEMORY_FLAG_PERSIST() {
        return winnt_h$constants$13.WRITE_NV_MEMORY_FLAG_PERSIST();
    }
    public static @C("int") int WRITE_NV_MEMORY_FLAG_NO_DRAIN() {
        return winnt_h$constants$13.WRITE_NV_MEMORY_FLAG_NO_DRAIN();
    }
    public static @C("int") int FILL_NV_MEMORY_FLAG_FLUSH() {
        return winnt_h$constants$13.FILL_NV_MEMORY_FLAG_FLUSH();
    }
    public static @C("int") int FILL_NV_MEMORY_FLAG_NON_TEMPORAL() {
        return winnt_h$constants$13.FILL_NV_MEMORY_FLAG_NON_TEMPORAL();
    }
    public static @C("int") int FILL_NV_MEMORY_FLAG_PERSIST() {
        return winnt_h$constants$13.FILL_NV_MEMORY_FLAG_PERSIST();
    }
    public static @C("int") int FILL_NV_MEMORY_FLAG_NO_DRAIN() {
        return winnt_h$constants$13.FILL_NV_MEMORY_FLAG_NO_DRAIN();
    }
    public static @C("char") byte RTL_CORRELATION_VECTOR_VERSION_1() {
        return winnt_h$constants$13.RTL_CORRELATION_VECTOR_VERSION_1();
    }
    public static @C("char") byte RTL_CORRELATION_VECTOR_VERSION_2() {
        return winnt_h$constants$13.RTL_CORRELATION_VECTOR_VERSION_2();
    }
    public static @C("char") byte RTL_CORRELATION_VECTOR_VERSION_CURRENT() {
        return winnt_h$constants$13.RTL_CORRELATION_VECTOR_VERSION_CURRENT();
    }
    public static @C("int") int RTL_CORRELATION_VECTOR_V1_PREFIX_LENGTH() {
        return winnt_h$constants$13.RTL_CORRELATION_VECTOR_V1_PREFIX_LENGTH();
    }
    public static @C("int") int RTL_CORRELATION_VECTOR_V1_LENGTH() {
        return winnt_h$constants$13.RTL_CORRELATION_VECTOR_V1_LENGTH();
    }
    public static @C("int") int RTL_CORRELATION_VECTOR_V2_PREFIX_LENGTH() {
        return winnt_h$constants$13.RTL_CORRELATION_VECTOR_V2_PREFIX_LENGTH();
    }
    public static @C("int") int RTL_CORRELATION_VECTOR_V2_LENGTH() {
        return winnt_h$constants$13.RTL_CORRELATION_VECTOR_V2_LENGTH();
    }
    public static @C("char*") MemorySegment IMAGE_POLICY_SECTION_NAME() {
        return winnt_h$constants$13.IMAGE_POLICY_SECTION_NAME();
    }
    public static @C("unsigned int") int RTL_CRITICAL_SECTION_ALL_FLAG_BITS() {
        return winnt_h$constants$13.RTL_CRITICAL_SECTION_ALL_FLAG_BITS();
    }
    public static @C("unsigned int") int RTL_CRITICAL_SECTION_FLAG_RESERVED() {
        return winnt_h$constants$13.RTL_CRITICAL_SECTION_FLAG_RESERVED();
    }
    public static @C("int") int ACTIVATION_CONTEXT_PATH_TYPE_NONE() {
        return winnt_h$constants$13.ACTIVATION_CONTEXT_PATH_TYPE_NONE();
    }
    public static @C("int") int ACTIVATION_CONTEXT_PATH_TYPE_WIN32_FILE() {
        return winnt_h$constants$13.ACTIVATION_CONTEXT_PATH_TYPE_WIN32_FILE();
    }
    public static @C("int") int ACTIVATION_CONTEXT_PATH_TYPE_URL() {
        return winnt_h$constants$13.ACTIVATION_CONTEXT_PATH_TYPE_URL();
    }
    public static @C("int") int ACTIVATION_CONTEXT_PATH_TYPE_ASSEMBLYREF() {
        return winnt_h$constants$13.ACTIVATION_CONTEXT_PATH_TYPE_ASSEMBLYREF();
    }
    public static @C("unsigned short*") MemorySegment UNIFIEDBUILDREVISION_KEY() {
        return winnt_h$constants$13.UNIFIEDBUILDREVISION_KEY();
    }
    public static @C("unsigned short*") MemorySegment UNIFIEDBUILDREVISION_VALUE() {
        return winnt_h$constants$13.UNIFIEDBUILDREVISION_VALUE();
    }
    public static @C("unsigned short*") MemorySegment DEVICEFAMILYDEVICEFORM_KEY() {
        return winnt_h$constants$13.DEVICEFAMILYDEVICEFORM_KEY();
    }
    public static @C("unsigned short*") MemorySegment DEVICEFAMILYDEVICEFORM_VALUE() {
        return winnt_h$constants$13.DEVICEFAMILYDEVICEFORM_VALUE();
    }
    public static @C("int") int KEY_QUERY_VALUE() {
        return winnt_h$constants$13.KEY_QUERY_VALUE();
    }
    public static @C("int") int KEY_SET_VALUE() {
        return winnt_h$constants$13.KEY_SET_VALUE();
    }
    public static @C("int") int KEY_CREATE_SUB_KEY() {
        return winnt_h$constants$13.KEY_CREATE_SUB_KEY();
    }
    public static @C("int") int KEY_ENUMERATE_SUB_KEYS() {
        return winnt_h$constants$13.KEY_ENUMERATE_SUB_KEYS();
    }
    public static @C("int") int KEY_NOTIFY() {
        return winnt_h$constants$13.KEY_NOTIFY();
    }
    public static @C("int") int KEY_CREATE_LINK() {
        return winnt_h$constants$13.KEY_CREATE_LINK();
    }
    public static @C("int") int KEY_WOW64_32KEY() {
        return winnt_h$constants$13.KEY_WOW64_32KEY();
    }
    public static @C("int") int KEY_WOW64_64KEY() {
        return winnt_h$constants$13.KEY_WOW64_64KEY();
    }
    public static @C("int") int KEY_WOW64_RES() {
        return winnt_h$constants$13.KEY_WOW64_RES();
    }
    public static @C("long") int KEY_READ() {
        return winnt_h$constants$13.KEY_READ();
    }
    public static @C("long") int KEY_WRITE() {
        return winnt_h$constants$13.KEY_WRITE();
    }
    public static @C("long") int KEY_EXECUTE() {
        return winnt_h$constants$13.KEY_EXECUTE();
    }
    public static @C("long") int KEY_ALL_ACCESS() {
        return winnt_h$constants$13.KEY_ALL_ACCESS();
    }
    public static @C("long") int REG_OPTION_RESERVED() {
        return winnt_h$constants$13.REG_OPTION_RESERVED();
    }
    public static @C("long") int REG_OPTION_NON_VOLATILE() {
        return winnt_h$constants$13.REG_OPTION_NON_VOLATILE();
    }
    public static @C("long") int REG_OPTION_VOLATILE() {
        return winnt_h$constants$13.REG_OPTION_VOLATILE();
    }
    public static @C("long") int REG_OPTION_CREATE_LINK() {
        return winnt_h$constants$13.REG_OPTION_CREATE_LINK();
    }
    public static @C("long") int REG_OPTION_BACKUP_RESTORE() {
        return winnt_h$constants$13.REG_OPTION_BACKUP_RESTORE();
    }
    public static @C("long") int REG_OPTION_OPEN_LINK() {
        return winnt_h$constants$13.REG_OPTION_OPEN_LINK();
    }
    public static @C("long") int REG_OPTION_DONT_VIRTUALIZE() {
        return winnt_h$constants$13.REG_OPTION_DONT_VIRTUALIZE();
    }
    public static @C("long") int REG_LEGAL_OPTION() {
        return winnt_h$constants$13.REG_LEGAL_OPTION();
    }
    public static @C("long") int REG_OPEN_LEGAL_OPTION() {
        return winnt_h$constants$13.REG_OPEN_LEGAL_OPTION();
    }
    public static @C("long") int REG_CREATED_NEW_KEY() {
        return winnt_h$constants$13.REG_CREATED_NEW_KEY();
    }
    public static @C("long") int REG_OPENED_EXISTING_KEY() {
        return winnt_h$constants$13.REG_OPENED_EXISTING_KEY();
    }
    public static @C("long") int REG_WHOLE_HIVE_VOLATILE() {
        return winnt_h$constants$13.REG_WHOLE_HIVE_VOLATILE();
    }
    public static @C("long") int REG_REFRESH_HIVE() {
        return winnt_h$constants$13.REG_REFRESH_HIVE();
    }
    public static @C("long") int REG_NO_LAZY_FLUSH() {
        return winnt_h$constants$13.REG_NO_LAZY_FLUSH();
    }
    public static @C("long") int REG_FORCE_RESTORE() {
        return winnt_h$constants$13.REG_FORCE_RESTORE();
    }
    public static @C("long") int REG_APP_HIVE() {
        return winnt_h$constants$13.REG_APP_HIVE();
    }
    public static @C("long") int REG_PROCESS_PRIVATE() {
        return winnt_h$constants$13.REG_PROCESS_PRIVATE();
    }
    public static @C("long") int REG_START_JOURNAL() {
        return winnt_h$constants$13.REG_START_JOURNAL();
    }
    public static @C("long") int REG_HIVE_EXACT_FILE_GROWTH() {
        return winnt_h$constants$13.REG_HIVE_EXACT_FILE_GROWTH();
    }
    public static @C("long") int REG_HIVE_NO_RM() {
        return winnt_h$constants$13.REG_HIVE_NO_RM();
    }
    public static @C("long") int REG_HIVE_SINGLE_LOG() {
        return winnt_h$constants$13.REG_HIVE_SINGLE_LOG();
    }
    public static @C("long") int REG_BOOT_HIVE() {
        return winnt_h$constants$13.REG_BOOT_HIVE();
    }
    public static @C("long") int REG_LOAD_HIVE_OPEN_HANDLE() {
        return winnt_h$constants$13.REG_LOAD_HIVE_OPEN_HANDLE();
    }
    public static @C("long") int REG_FLUSH_HIVE_FILE_GROWTH() {
        return winnt_h$constants$13.REG_FLUSH_HIVE_FILE_GROWTH();
    }
    public static @C("long") int REG_OPEN_READ_ONLY() {
        return winnt_h$constants$13.REG_OPEN_READ_ONLY();
    }
    public static @C("long") int REG_IMMUTABLE() {
        return winnt_h$constants$13.REG_IMMUTABLE();
    }
    public static @C("long") int REG_NO_IMPERSONATION_FALLBACK() {
        return winnt_h$constants$13.REG_NO_IMPERSONATION_FALLBACK();
    }
    public static @C("long") int REG_APP_HIVE_OPEN_READ_ONLY() {
        return winnt_h$constants$13.REG_APP_HIVE_OPEN_READ_ONLY();
    }
    public static @C("int") int REG_UNLOAD_LEGAL_FLAGS() {
        return winnt_h$constants$13.REG_UNLOAD_LEGAL_FLAGS();
    }
    public static @C("long") int REG_NOTIFY_CHANGE_NAME() {
        return winnt_h$constants$13.REG_NOTIFY_CHANGE_NAME();
    }
    public static @C("long") int REG_NOTIFY_CHANGE_ATTRIBUTES() {
        return winnt_h$constants$13.REG_NOTIFY_CHANGE_ATTRIBUTES();
    }
    public static @C("long") int REG_NOTIFY_CHANGE_LAST_SET() {
        return winnt_h$constants$13.REG_NOTIFY_CHANGE_LAST_SET();
    }
    public static @C("long") int REG_NOTIFY_CHANGE_SECURITY() {
        return winnt_h$constants$13.REG_NOTIFY_CHANGE_SECURITY();
    }
    public static @C("long") int REG_NOTIFY_THREAD_AGNOSTIC() {
        return winnt_h$constants$13.REG_NOTIFY_THREAD_AGNOSTIC();
    }
    public static @C("long") int REG_LEGAL_CHANGE_FILTER() {
        return winnt_h$constants$13.REG_LEGAL_CHANGE_FILTER();
    }
    public static @C("unsigned long") int REG_NONE() {
        return winnt_h$constants$13.REG_NONE();
    }
    public static @C("unsigned long") int REG_SZ() {
        return winnt_h$constants$13.REG_SZ();
    }
    public static @C("unsigned long") int REG_EXPAND_SZ() {
        return winnt_h$constants$13.REG_EXPAND_SZ();
    }
    public static @C("unsigned long") int REG_BINARY() {
        return winnt_h$constants$13.REG_BINARY();
    }
    public static @C("unsigned long") int REG_DWORD() {
        return winnt_h$constants$13.REG_DWORD();
    }
    public static @C("unsigned long") int REG_DWORD_LITTLE_ENDIAN() {
        return winnt_h$constants$13.REG_DWORD_LITTLE_ENDIAN();
    }
    public static @C("unsigned long") int REG_DWORD_BIG_ENDIAN() {
        return winnt_h$constants$13.REG_DWORD_BIG_ENDIAN();
    }
    public static @C("unsigned long") int REG_LINK() {
        return winnt_h$constants$13.REG_LINK();
    }
    public static @C("unsigned long") int REG_MULTI_SZ() {
        return winnt_h$constants$13.REG_MULTI_SZ();
    }
    public static @C("unsigned long") int REG_RESOURCE_LIST() {
        return winnt_h$constants$13.REG_RESOURCE_LIST();
    }
    public static @C("unsigned long") int REG_FULL_RESOURCE_DESCRIPTOR() {
        return winnt_h$constants$13.REG_FULL_RESOURCE_DESCRIPTOR();
    }
    public static @C("unsigned long") int REG_RESOURCE_REQUIREMENTS_LIST() {
        return winnt_h$constants$13.REG_RESOURCE_REQUIREMENTS_LIST();
    }
    public static @C("unsigned long") int REG_QWORD() {
        return winnt_h$constants$13.REG_QWORD();
    }
    public static @C("unsigned long") int REG_QWORD_LITTLE_ENDIAN() {
        return winnt_h$constants$13.REG_QWORD_LITTLE_ENDIAN();
    }
    public static @C("int") int SERVICE_DRIVER() {
        return winnt_h$constants$13.SERVICE_DRIVER();
    }
    public static @C("int") int SERVICE_WIN32() {
        return winnt_h$constants$13.SERVICE_WIN32();
    }
    public static @C("int") int SERVICE_USER_SHARE_PROCESS() {
        return winnt_h$constants$13.SERVICE_USER_SHARE_PROCESS();
    }
    public static @C("int") int SERVICE_USER_OWN_PROCESS() {
        return winnt_h$constants$13.SERVICE_USER_OWN_PROCESS();
    }
    public static @C("int") int SERVICE_TYPE_ALL() {
        return winnt_h$constants$13.SERVICE_TYPE_ALL();
    }
    public static @C("int") int CM_SERVICE_VALID_PROMOTION_MASK() {
        return winnt_h$constants$13.CM_SERVICE_VALID_PROMOTION_MASK();
    }
    public static @C("long") int TAPE_ERASE_SHORT() {
        return winnt_h$constants$13.TAPE_ERASE_SHORT();
    }
    public static @C("long") int TAPE_ERASE_LONG() {
        return winnt_h$constants$13.TAPE_ERASE_LONG();
    }
    public static @C("long") int TAPE_LOAD() {
        return winnt_h$constants$13.TAPE_LOAD();
    }
    public static @C("long") int TAPE_UNLOAD() {
        return winnt_h$constants$13.TAPE_UNLOAD();
    }
    public static @C("long") int TAPE_TENSION() {
        return winnt_h$constants$13.TAPE_TENSION();
    }
    public static @C("long") int TAPE_LOCK() {
        return winnt_h$constants$13.TAPE_LOCK();
    }
    public static @C("long") int TAPE_UNLOCK() {
        return winnt_h$constants$13.TAPE_UNLOCK();
    }
    public static @C("long") int TAPE_FORMAT() {
        return winnt_h$constants$13.TAPE_FORMAT();
    }
    public static @C("long") int TAPE_SETMARKS() {
        return winnt_h$constants$13.TAPE_SETMARKS();
    }
    public static @C("long") int TAPE_FILEMARKS() {
        return winnt_h$constants$13.TAPE_FILEMARKS();
    }
    public static @C("long") int TAPE_SHORT_FILEMARKS() {
        return winnt_h$constants$13.TAPE_SHORT_FILEMARKS();
    }
    public static @C("long") int TAPE_LONG_FILEMARKS() {
        return winnt_h$constants$13.TAPE_LONG_FILEMARKS();
    }
    public static @C("long") int TAPE_ABSOLUTE_POSITION() {
        return winnt_h$constants$13.TAPE_ABSOLUTE_POSITION();
    }
    public static @C("long") int TAPE_LOGICAL_POSITION() {
        return winnt_h$constants$13.TAPE_LOGICAL_POSITION();
    }
    public static @C("long") int TAPE_PSEUDO_LOGICAL_POSITION() {
        return winnt_h$constants$13.TAPE_PSEUDO_LOGICAL_POSITION();
    }
    public static @C("long") int TAPE_REWIND() {
        return winnt_h$constants$13.TAPE_REWIND();
    }
    public static @C("long") int TAPE_ABSOLUTE_BLOCK() {
        return winnt_h$constants$13.TAPE_ABSOLUTE_BLOCK();
    }
    public static @C("long") int TAPE_LOGICAL_BLOCK() {
        return winnt_h$constants$13.TAPE_LOGICAL_BLOCK();
    }
    public static @C("long") int TAPE_PSEUDO_LOGICAL_BLOCK() {
        return winnt_h$constants$13.TAPE_PSEUDO_LOGICAL_BLOCK();
    }
    public static @C("long") int TAPE_SPACE_END_OF_DATA() {
        return winnt_h$constants$13.TAPE_SPACE_END_OF_DATA();
    }
    public static @C("long") int TAPE_SPACE_RELATIVE_BLOCKS() {
        return winnt_h$constants$13.TAPE_SPACE_RELATIVE_BLOCKS();
    }
    public static @C("long") int TAPE_SPACE_FILEMARKS() {
        return winnt_h$constants$13.TAPE_SPACE_FILEMARKS();
    }
    public static @C("long") int TAPE_SPACE_SEQUENTIAL_FMKS() {
        return winnt_h$constants$13.TAPE_SPACE_SEQUENTIAL_FMKS();
    }
    public static @C("long") int TAPE_SPACE_SETMARKS() {
        return winnt_h$constants$13.TAPE_SPACE_SETMARKS();
    }
    public static @C("long") int TAPE_SPACE_SEQUENTIAL_SMKS() {
        return winnt_h$constants$13.TAPE_SPACE_SEQUENTIAL_SMKS();
    }
    public static @C("unsigned int") int TAPE_DRIVE_RESERVED_BIT() {
        return winnt_h$constants$13.TAPE_DRIVE_RESERVED_BIT();
    }
    public static @C("unsigned int") int TAPE_DRIVE_LOAD_UNLOAD() {
        return winnt_h$constants$13.TAPE_DRIVE_LOAD_UNLOAD();
    }
    public static @C("unsigned int") int TAPE_DRIVE_TENSION() {
        return winnt_h$constants$13.TAPE_DRIVE_TENSION();
    }
    public static @C("unsigned int") int TAPE_DRIVE_LOCK_UNLOCK() {
        return winnt_h$constants$13.TAPE_DRIVE_LOCK_UNLOCK();
    }
    public static @C("unsigned int") int TAPE_DRIVE_REWIND_IMMEDIATE() {
        return winnt_h$constants$13.TAPE_DRIVE_REWIND_IMMEDIATE();
    }
    public static @C("unsigned int") int TAPE_DRIVE_SET_BLOCK_SIZE() {
        return winnt_h$constants$13.TAPE_DRIVE_SET_BLOCK_SIZE();
    }
    public static @C("unsigned int") int TAPE_DRIVE_LOAD_UNLD_IMMED() {
        return winnt_h$constants$13.TAPE_DRIVE_LOAD_UNLD_IMMED();
    }
    public static @C("unsigned int") int TAPE_DRIVE_TENSION_IMMED() {
        return winnt_h$constants$13.TAPE_DRIVE_TENSION_IMMED();
    }
    public static @C("unsigned int") int TAPE_DRIVE_LOCK_UNLK_IMMED() {
        return winnt_h$constants$13.TAPE_DRIVE_LOCK_UNLK_IMMED();
    }
    public static @C("unsigned int") int TAPE_DRIVE_SET_ECC() {
        return winnt_h$constants$13.TAPE_DRIVE_SET_ECC();
    }
    public static @C("unsigned int") int TAPE_DRIVE_SET_COMPRESSION() {
        return winnt_h$constants$13.TAPE_DRIVE_SET_COMPRESSION();
    }
    public static @C("unsigned int") int TAPE_DRIVE_SET_PADDING() {
        return winnt_h$constants$13.TAPE_DRIVE_SET_PADDING();
    }
    public static @C("unsigned int") int TAPE_DRIVE_SET_REPORT_SMKS() {
        return winnt_h$constants$13.TAPE_DRIVE_SET_REPORT_SMKS();
    }
    public static @C("unsigned int") int TAPE_DRIVE_ABSOLUTE_BLK() {
        return winnt_h$constants$13.TAPE_DRIVE_ABSOLUTE_BLK();
    }
    public static @C("unsigned int") int TAPE_DRIVE_ABS_BLK_IMMED() {
        return winnt_h$constants$13.TAPE_DRIVE_ABS_BLK_IMMED();
    }
    public static @C("unsigned int") int TAPE_DRIVE_LOGICAL_BLK() {
        return winnt_h$constants$13.TAPE_DRIVE_LOGICAL_BLK();
    }
    public static @C("unsigned int") int TAPE_DRIVE_LOG_BLK_IMMED() {
        return winnt_h$constants$13.TAPE_DRIVE_LOG_BLK_IMMED();
    }
    public static @C("unsigned int") int TAPE_DRIVE_END_OF_DATA() {
        return winnt_h$constants$13.TAPE_DRIVE_END_OF_DATA();
    }
    public static @C("unsigned int") int TAPE_DRIVE_RELATIVE_BLKS() {
        return winnt_h$constants$13.TAPE_DRIVE_RELATIVE_BLKS();
    }
    public static @C("unsigned int") int TAPE_DRIVE_FILEMARKS() {
        return winnt_h$constants$13.TAPE_DRIVE_FILEMARKS();
    }
    public static @C("unsigned int") int TAPE_DRIVE_SEQUENTIAL_FMKS() {
        return winnt_h$constants$13.TAPE_DRIVE_SEQUENTIAL_FMKS();
    }
    public static @C("unsigned int") int TAPE_DRIVE_SETMARKS() {
        return winnt_h$constants$13.TAPE_DRIVE_SETMARKS();
    }
    public static @C("unsigned int") int TAPE_DRIVE_SEQUENTIAL_SMKS() {
        return winnt_h$constants$13.TAPE_DRIVE_SEQUENTIAL_SMKS();
    }
    public static @C("unsigned int") int TAPE_DRIVE_REVERSE_POSITION() {
        return winnt_h$constants$13.TAPE_DRIVE_REVERSE_POSITION();
    }
    public static @C("unsigned int") int TAPE_DRIVE_SPACE_IMMEDIATE() {
        return winnt_h$constants$13.TAPE_DRIVE_SPACE_IMMEDIATE();
    }
    public static @C("unsigned int") int TAPE_DRIVE_WRITE_SETMARKS() {
        return winnt_h$constants$13.TAPE_DRIVE_WRITE_SETMARKS();
    }
    public static @C("unsigned int") int TAPE_DRIVE_WRITE_FILEMARKS() {
        return winnt_h$constants$13.TAPE_DRIVE_WRITE_FILEMARKS();
    }
    public static @C("unsigned int") int TAPE_DRIVE_WRITE_SHORT_FMKS() {
        return winnt_h$constants$13.TAPE_DRIVE_WRITE_SHORT_FMKS();
    }
    public static @C("unsigned int") int TAPE_DRIVE_WRITE_LONG_FMKS() {
        return winnt_h$constants$13.TAPE_DRIVE_WRITE_LONG_FMKS();
    }
    public static @C("unsigned int") int TAPE_DRIVE_WRITE_MARK_IMMED() {
        return winnt_h$constants$13.TAPE_DRIVE_WRITE_MARK_IMMED();
    }
    public static @C("unsigned int") int TAPE_DRIVE_FORMAT() {
        return winnt_h$constants$13.TAPE_DRIVE_FORMAT();
    }
    public static @C("unsigned int") int TAPE_DRIVE_FORMAT_IMMEDIATE() {
        return winnt_h$constants$13.TAPE_DRIVE_FORMAT_IMMEDIATE();
    }
    public static @C("unsigned int") int TAPE_DRIVE_HIGH_FEATURES() {
        return winnt_h$constants$13.TAPE_DRIVE_HIGH_FEATURES();
    }
    public static @C("long") int TAPE_FIXED_PARTITIONS() {
        return winnt_h$constants$13.TAPE_FIXED_PARTITIONS();
    }
    public static @C("long") int TAPE_SELECT_PARTITIONS() {
        return winnt_h$constants$13.TAPE_SELECT_PARTITIONS();
    }
    public static @C("long") int TAPE_INITIATOR_PARTITIONS() {
        return winnt_h$constants$13.TAPE_INITIATOR_PARTITIONS();
    }
    public static @C("long") int TAPE_QUERY_DRIVE_PARAMETERS() {
        return winnt_h$constants$13.TAPE_QUERY_DRIVE_PARAMETERS();
    }
    public static @C("long") int TAPE_QUERY_MEDIA_CAPACITY() {
        return winnt_h$constants$13.TAPE_QUERY_MEDIA_CAPACITY();
    }
    public static @C("long") int TAPE_CHECK_FOR_DRIVE_PROBLEM() {
        return winnt_h$constants$13.TAPE_CHECK_FOR_DRIVE_PROBLEM();
    }
    public static @C("long") int TAPE_QUERY_IO_ERROR_DATA() {
        return winnt_h$constants$13.TAPE_QUERY_IO_ERROR_DATA();
    }
    public static @C("long") int TAPE_QUERY_DEVICE_ERROR_DATA() {
        return winnt_h$constants$13.TAPE_QUERY_DEVICE_ERROR_DATA();
    }
    public static @C("int") int TRANSACTIONMANAGER_QUERY_INFORMATION() {
        return winnt_h$constants$13.TRANSACTIONMANAGER_QUERY_INFORMATION();
    }
    public static @C("int") int TRANSACTIONMANAGER_SET_INFORMATION() {
        return winnt_h$constants$13.TRANSACTIONMANAGER_SET_INFORMATION();
    }
    public static @C("int") int TRANSACTIONMANAGER_RECOVER() {
        return winnt_h$constants$13.TRANSACTIONMANAGER_RECOVER();
    }
    public static @C("int") int TRANSACTIONMANAGER_RENAME() {
        return winnt_h$constants$13.TRANSACTIONMANAGER_RENAME();
    }
    public static @C("int") int TRANSACTIONMANAGER_CREATE_RM() {
        return winnt_h$constants$13.TRANSACTIONMANAGER_CREATE_RM();
    }
    public static @C("int") int TRANSACTIONMANAGER_BIND_TRANSACTION() {
        return winnt_h$constants$13.TRANSACTIONMANAGER_BIND_TRANSACTION();
    }
    public static @C("long") int TRANSACTIONMANAGER_GENERIC_READ() {
        return winnt_h$constants$13.TRANSACTIONMANAGER_GENERIC_READ();
    }
    public static @C("long") int TRANSACTIONMANAGER_GENERIC_WRITE() {
        return winnt_h$constants$13.TRANSACTIONMANAGER_GENERIC_WRITE();
    }
    public static @C("long") int TRANSACTIONMANAGER_GENERIC_EXECUTE() {
        return winnt_h$constants$13.TRANSACTIONMANAGER_GENERIC_EXECUTE();
    }
    public static @C("long") int TRANSACTIONMANAGER_ALL_ACCESS() {
        return winnt_h$constants$13.TRANSACTIONMANAGER_ALL_ACCESS();
    }
    public static @C("int") int TRANSACTION_QUERY_INFORMATION() {
        return winnt_h$constants$13.TRANSACTION_QUERY_INFORMATION();
    }
    public static @C("int") int TRANSACTION_SET_INFORMATION() {
        return winnt_h$constants$13.TRANSACTION_SET_INFORMATION();
    }
    public static @C("int") int TRANSACTION_ENLIST() {
        return winnt_h$constants$13.TRANSACTION_ENLIST();
    }
    public static @C("int") int TRANSACTION_COMMIT() {
        return winnt_h$constants$13.TRANSACTION_COMMIT();
    }
    public static @C("int") int TRANSACTION_ROLLBACK() {
        return winnt_h$constants$13.TRANSACTION_ROLLBACK();
    }
    public static @C("int") int TRANSACTION_PROPAGATE() {
        return winnt_h$constants$13.TRANSACTION_PROPAGATE();
    }
    public static @C("int") int TRANSACTION_RIGHT_RESERVED1() {
        return winnt_h$constants$13.TRANSACTION_RIGHT_RESERVED1();
    }
    public static @C("long") int TRANSACTION_GENERIC_READ() {
        return winnt_h$constants$13.TRANSACTION_GENERIC_READ();
    }
    public static @C("long") int TRANSACTION_GENERIC_WRITE() {
        return winnt_h$constants$13.TRANSACTION_GENERIC_WRITE();
    }
    public static @C("long") int TRANSACTION_GENERIC_EXECUTE() {
        return winnt_h$constants$13.TRANSACTION_GENERIC_EXECUTE();
    }
    public static @C("long") int TRANSACTION_ALL_ACCESS() {
        return winnt_h$constants$13.TRANSACTION_ALL_ACCESS();
    }
    public static @C("long") int TRANSACTION_RESOURCE_MANAGER_RIGHTS() {
        return winnt_h$constants$13.TRANSACTION_RESOURCE_MANAGER_RIGHTS();
    }
    public static @C("int") int RESOURCEMANAGER_QUERY_INFORMATION() {
        return winnt_h$constants$13.RESOURCEMANAGER_QUERY_INFORMATION();
    }
    public static @C("int") int RESOURCEMANAGER_SET_INFORMATION() {
        return winnt_h$constants$13.RESOURCEMANAGER_SET_INFORMATION();
    }
    public static @C("int") int RESOURCEMANAGER_RECOVER() {
        return winnt_h$constants$13.RESOURCEMANAGER_RECOVER();
    }
    public static @C("int") int RESOURCEMANAGER_ENLIST() {
        return winnt_h$constants$13.RESOURCEMANAGER_ENLIST();
    }
    public static @C("int") int RESOURCEMANAGER_GET_NOTIFICATION() {
        return winnt_h$constants$13.RESOURCEMANAGER_GET_NOTIFICATION();
    }
    public static @C("int") int RESOURCEMANAGER_REGISTER_PROTOCOL() {
        return winnt_h$constants$13.RESOURCEMANAGER_REGISTER_PROTOCOL();
    }
    public static @C("int") int RESOURCEMANAGER_COMPLETE_PROPAGATION() {
        return winnt_h$constants$13.RESOURCEMANAGER_COMPLETE_PROPAGATION();
    }
    public static @C("long") int RESOURCEMANAGER_GENERIC_READ() {
        return winnt_h$constants$13.RESOURCEMANAGER_GENERIC_READ();
    }
    public static @C("long") int RESOURCEMANAGER_GENERIC_WRITE() {
        return winnt_h$constants$13.RESOURCEMANAGER_GENERIC_WRITE();
    }
    public static @C("long") int RESOURCEMANAGER_GENERIC_EXECUTE() {
        return winnt_h$constants$13.RESOURCEMANAGER_GENERIC_EXECUTE();
    }
    public static @C("long") int RESOURCEMANAGER_ALL_ACCESS() {
        return winnt_h$constants$13.RESOURCEMANAGER_ALL_ACCESS();
    }
    public static @C("int") int ENLISTMENT_QUERY_INFORMATION() {
        return winnt_h$constants$13.ENLISTMENT_QUERY_INFORMATION();
    }
    public static @C("int") int ENLISTMENT_SET_INFORMATION() {
        return winnt_h$constants$13.ENLISTMENT_SET_INFORMATION();
    }
    public static @C("int") int ENLISTMENT_RECOVER() {
        return winnt_h$constants$13.ENLISTMENT_RECOVER();
    }
    public static @C("int") int ENLISTMENT_SUBORDINATE_RIGHTS() {
        return winnt_h$constants$13.ENLISTMENT_SUBORDINATE_RIGHTS();
    }
    public static @C("int") int ENLISTMENT_SUPERIOR_RIGHTS() {
        return winnt_h$constants$13.ENLISTMENT_SUPERIOR_RIGHTS();
    }
    public static @C("long") int ENLISTMENT_GENERIC_READ() {
        return winnt_h$constants$13.ENLISTMENT_GENERIC_READ();
    }
    public static @C("long") int ENLISTMENT_GENERIC_WRITE() {
        return winnt_h$constants$13.ENLISTMENT_GENERIC_WRITE();
    }
    public static @C("long") int ENLISTMENT_GENERIC_EXECUTE() {
        return winnt_h$constants$13.ENLISTMENT_GENERIC_EXECUTE();
    }
    public static @C("long") int ENLISTMENT_ALL_ACCESS() {
        return winnt_h$constants$13.ENLISTMENT_ALL_ACCESS();
    }
    public static @C("int") int ACTIVATION_CONTEXT_SECTION_ASSEMBLY_INFORMATION() {
        return winnt_h$constants$13.ACTIVATION_CONTEXT_SECTION_ASSEMBLY_INFORMATION();
    }
    public static @C("int") int ACTIVATION_CONTEXT_SECTION_DLL_REDIRECTION() {
        return winnt_h$constants$13.ACTIVATION_CONTEXT_SECTION_DLL_REDIRECTION();
    }
    public static @C("int") int ACTIVATION_CONTEXT_SECTION_WINDOW_CLASS_REDIRECTION() {
        return winnt_h$constants$13.ACTIVATION_CONTEXT_SECTION_WINDOW_CLASS_REDIRECTION();
    }
    public static @C("int") int ACTIVATION_CONTEXT_SECTION_COM_SERVER_REDIRECTION() {
        return winnt_h$constants$13.ACTIVATION_CONTEXT_SECTION_COM_SERVER_REDIRECTION();
    }
    public static @C("int") int ACTIVATION_CONTEXT_SECTION_COM_INTERFACE_REDIRECTION() {
        return winnt_h$constants$13.ACTIVATION_CONTEXT_SECTION_COM_INTERFACE_REDIRECTION();
    }
    public static @C("int") int ACTIVATION_CONTEXT_SECTION_COM_TYPE_LIBRARY_REDIRECTION() {
        return winnt_h$constants$13.ACTIVATION_CONTEXT_SECTION_COM_TYPE_LIBRARY_REDIRECTION();
    }
    public static @C("int") int ACTIVATION_CONTEXT_SECTION_COM_PROGID_REDIRECTION() {
        return winnt_h$constants$13.ACTIVATION_CONTEXT_SECTION_COM_PROGID_REDIRECTION();
    }
    public static @C("int") int ACTIVATION_CONTEXT_SECTION_GLOBAL_OBJECT_RENAME_TABLE() {
        return winnt_h$constants$13.ACTIVATION_CONTEXT_SECTION_GLOBAL_OBJECT_RENAME_TABLE();
    }
    public static @C("int") int ACTIVATION_CONTEXT_SECTION_CLR_SURROGATES() {
        return winnt_h$constants$13.ACTIVATION_CONTEXT_SECTION_CLR_SURROGATES();
    }
    public static @C("int") int ACTIVATION_CONTEXT_SECTION_APPLICATION_SETTINGS() {
        return winnt_h$constants$13.ACTIVATION_CONTEXT_SECTION_APPLICATION_SETTINGS();
    }
    public static @C("int") int ACTIVATION_CONTEXT_SECTION_COMPATIBILITY_INFO() {
        return winnt_h$constants$13.ACTIVATION_CONTEXT_SECTION_COMPATIBILITY_INFO();
    }
    public static @C("int") int ACTIVATION_CONTEXT_SECTION_WINRT_ACTIVATABLE_CLASSES() {
        return winnt_h$constants$13.ACTIVATION_CONTEXT_SECTION_WINRT_ACTIVATABLE_CLASSES();
    }
}


