// Generated by jextract

package com.github.tornaia.foreign.win.api.winbase.internal;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import jdk.incubator.foreign.*;
import jdk.incubator.foreign.MemoryLayout.PathElement;
import static jdk.incubator.foreign.CLinker.*;
class winbase_h$constants$3 extends winbase_h$constants$2 {

    /* package-private */ winbase_h$constants$3() {}
}

